### ISSUE TITLE
Queries regarding future of bootstrap-vue-3

### ISSUE THREAD

**Issue by jd-0001** [cdmoro/bootstrap-vue-3#103]
Hi @cdmoro,

I am JD. We at [PIXINVENT](https://pixinvent.com/) created the most popular [Vuexy Admin Template](https://themeforest.net/item/vuexy-vuejs-html-laravel-admin-dashboard-template/23328599) based on BootstrapVue.

As people are asking for Vue 3, we are checking your framework and its feasibility of migration for our template. We have queries before we start working on it, it will help us proceeding further if you can spare some time to let us know about the below queries:

- When we can expect the BETA version of the framework?
- Do you have any roadmap for the progress of the framework? (GitHub project will be great)
- When documentation will get updated?
- Do you have a playground where we can play with components? (Like Vuetify have on their [docs](https://vuetifyjs.com/en/components/alerts/#usage))

We are looking forward to your reply.

Regards.

**Comment by cdmoro** [comment]
Hello there!
First of all, I wanna thank you, this kind of things is what encourages us to keep up working on this library. 
- About the BETA version, although there is a lot of work to do, with every commit and PR we are getting close to have a BETA version. I think I could create a roadmap to clarify the path of this project.
- Documentation is getting updated a bit slowly, I have to confess, but today I publish a new release (v0.0.4) with a lot of new documentation. When BETA version comes out we hope to have completed the documentation.
- Regarding the playground, we could improve the actual documentation files to make it more interactive. What do you think about BootstrapVue playground? https://bootstrap-vue.org/play

Thanks again,
regards

**Comment by lampsbr** [comment]
I met this project last friday, asked something similar last saturday (but on twitter), and today I'm already seeing a huge documentation update. Congrats!

Maybe it could be positive if we also gather in some instant messaging channel, like a discord server, gitter etc, so users could be able to clear each other's questions too. I just tried the b-table component and it seems to be working, despite having no documentation yet. Should I assume that most of boostrapvue's components are already working?

**Comment by jd-0001** [comment]
Thanks @cdmoro for replying. You are doing really great :heart: 

As I got answers I should close this now.
