### ISSUE TITLE
Release as a Package?

### ISSUE THREAD

**Issue by Makiyu-py** [cdmoro/bootstrap-vue-3#11]
I've been trying to search on yarn, docs and the source code on how to install only to realize that it's been marked private on the package.json file.

My question is, when will this be released as a yarn/npm package? Do you guys have plans on doing so?

Thanks in advance!

**Comment by cdmoro** [comment]
Hello there! We've just published the package (0.0.1-alpha-1 version) in the npm registry :smile: 
Try running `yarn add bootstrap-vue-3` or `npm i bootstrap-vue-3`, remember you need to install `bootstrap` and import the CSS manually.

**Comment by Makiyu-py** [comment]
Noted!
