### ISSUE TITLE
Cannot use $bvModal.hide or show

### ISSUE THREAD

**Issue by loksoon** [cdmoro/bootstrap-vue-3#120]
Uncaught TypeError: _ctx.$bvModal is undefined
![Screenshot 2021-09-30 at 19 27 53](https://user-images.githubusercontent.com/43371272/135447059-42bc6604-83bb-4e9a-a9cc-a1ea526cef4d.png)
ed

**Comment by cdmoro** [comment]
That's right! we haven't implemented that functionality yet. At the beginning of this project, I implemented the very first version of $bvModal, there is a function called useModal (it isn't documented but you can import it).

Honestly, I don't know which is the best strategy. If we should use [global properties](https://v3.vuejs.org/guide/migration/global-api.html#vue-prototype-replaced-by-config-globalproperties) or create a composable.

**Comment by loksoon** [comment]
Thanks for a commented

**Comment by loksoon** [comment]
Em i cannot find the useModal function inside your code

**Comment by Don-Maxon** [comment]
when will Modal be added ?

**Comment by Kenvdb** [comment]
> when will Modal be added ?

Yeah same here, interested to know.

**Comment by xvaara** [comment]
There is modal, just that $bvModal isn't the way you do things in vue3, use a variable or create a reactive state.

**Comment by L422Y** [comment]
The problem here is that if you use `v-b-modal`, there's no good / clean way to programmatically close modals without interacting with the DOM.

```
    <b-button v-b-modal.add-new-modal>Add New</b-button>              
```

**Comment by asika32764** [comment]
For someone who is looking for closing BModal programmatically in child components, this works for me:

```ts
import { type ComponentInternalInstance, getCurrentInstance } from 'vue';

export function useClosestModal() {
  const instance = getCurrentInstance();

  if (!instance) {
    return null;
  }

  const modalComponent = findBModal(instance);

  if (!modalComponent) {
    return null;
  }

  return {
    show() {
      return modalComponent.exposed?.show()
    },
    hide(trigger = '') {
      return modalComponent.exposed?.hide(trigger)
    }
  };
}

function findBModal(component: ComponentInternalInstance) {
  if (!component.parent) {
    return null;
  }

  if (component.parent.type.__name === 'BModal') {
    return component.parent;
  }

  return findBModal(component.parent);
}

```

usage:

```ts
const currentModal = useClosestModal()!;

currentModal.hide();
```

**Comment by VividLemon** [comment]
> For someone who is looking for closing BModal programmatically in child components, this works for me:
> 
> ```ts
> import { type ComponentInternalInstance, getCurrentInstance } from 'vue';
> 
> export function useClosestModal() {
>   const instance = getCurrentInstance();
> 
>   if (!instance) {
>     return null;
>   }
> 
>   const modalComponent = findBModal(instance);
> 
>   if (!modalComponent) {
>     return null;
>   }
> 
>   return {
>     show() {
>       return modalComponent.exposed?.show()
>     },
>     hide(trigger = '') {
>       return modalComponent.exposed?.hide(trigger)
>     }
>   };
> }
> 
> function findBModal(component: ComponentInternalInstance) {
>   if (!component.parent) {
>     return null;
>   }
> 
>   if (component.parent.type.__name === 'BModal') {
>     return component.parent;
>   }
> 
>   return findBModal(component.parent);
> }
> ```
> 
> usage:
> 
> ```ts
> const currentModal = useClosestModal()!;
> 
> currentModal.hide();
> ```
> 
> The better solution is that if we can get modal by ID.
> 
> ```ts
> const modal = useModal('#modal-id'); // get by ID
> 
> const modal = useModal(); // get closest
> ```
> 
> But I haven't implement this.

If you implement it, it can probably get merged

**Comment by asika32764** [comment]
A simple implementation here https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1430

**Comment by VividLemon** [comment]
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/modal.html#programmatically-control
