### ISSUE TITLE
Question: When can we expect b-table component?

### ISSUE THREAD

**Issue by Radouch** [cdmoro/bootstrap-vue-3#138]
At first, I just want to stress this is not any kind of complaint. :-)
I would just like to know if there is any expected (approximate) date when `b-table` component (with the functionality comparable with that one from the original Bootstrap-Vue) will be released. We really need to use such table component in our project so I need to decide if to wait for this library or try some other way.
Thanks to @cdmoro and all other contributers to this great project!

**Comment by lukematthews** [comment]
Adding to this, I started using this project today (haven't used bootstrap-vue because I'm on vue 3, but it's all looking good)

Is `b-table-simple` in the pipelines?

**Comment by comod** [comment]
How to use "select"-feature?
 (eg: `@row-selected="onRowSelected"`)
Or is this still not ready?

**Comment by protomors** [comment]
This is not yet implemented for tables.

**Comment by cdmoro** [comment]
> Adding to this, I started using this project today (haven't used bootstrap-vue because I'm on vue 3, but it's all looking good)
> 
> Is `b-table-simple` in the pipelines?

Correct me if I'm wrong, but `b-table-simple` component is just a wrapper for the HTML table, right? With a bunch of components: `b-td`, `b-th`, `b-tbody`, and so on. If that is the case, it would be relatively simple to implement those components.

**Comment by cdmoro** [comment]
@lukematthews here is the PR of `b-table-simple` #297 :smiley:

**Comment by enix-app** [comment]
Thanks to @cdmoro, I think the component I'm most looking forward to using is a fully featured table like BSV version 2.

**Comment by cmora-pe** [comment]
@cdmoro In this issue there are a couple of short changes that will help a lot meanwhile the tabel componente is ready. ¿Would you mind to check them? It's just a couple of lines, but make a real big change.

**Comment by alexdohm** [comment]
hi all, do you by any change have a timeline update for additional table features listed above, like sorting and filtering?

**Comment by devhus** [comment]
The BTable component will be almost complete when this PR https://github.com/cdmoro/bootstrap-vue-3/pull/643 gets completed & merged. Hopefully next release. 👍🏼
