### ISSUE TITLE
Question regarding BIcon size property

### ISSUE THREAD

**Issue by jclijmans** [cdmoro/bootstrap-vue-3#155]
The bootstrap-vue BIcon component does not have a size property. 
As stated in the documentation, 
- "Icons have a default width and height of 1em, which means they will scale with the size of the current font size"
- "You can also use custom CSS to set the icon size, either via direct style attribute, or via custom classes"
- "You can also use the prop font-scale to scale the icon's current font size by the specified factor"

The current implementation has the size property which sets the font-size. Should we leave it as a shortcut to use instead of custom css or remove it to be compatible with the bootstrap-vue implementation?

I don't want to break anyone's work.

**Comment by cdmoro** [comment]
Hello! Honestly, I don't remember who made our `b-icon` component, but I think we have to follow the bootstrap-vue implementation. So go ahead!

Did you include this chan get in your last PR (#154)? If not, It's a good opportunity to make that change.

Let me know what you think

**Comment by jclijmans** [comment]
The size property is still include.
But it works, so it's not removed.
