### ISSUE TITLE
parity checklist with bootstrap-vue

### ISSUE THREAD

**Issue by zoranpopovic** [cdmoro/bootstrap-vue-3#16]
Awesome to see this project grow into big set of components.   Code seems much more readable than the original project which i think will help with more contributors over time.  

Given that a number of us are looking for trying to experimentally switch, it would be great to have a list of covered and not-covered components, as well as full vs partial replication (prop/slot/functionality missing) with the bootstrap-vue lib.  This would be extremely helpful to know when coverage is good enough to start switching.  My guess is the more people try to switch, the more PRs this project will have.

**Comment by cdmoro** [comment]
This is a really good idea indeed! I could add a page to the docs with the status of the components. This curated list has to have the new features of bootstrap 5 also.

**Comment by cdmoro** [comment]
Here is the first version of the parity list https://cdmoro.github.io/bootstrap-vue-3/reference/parityList.html :smile:
Now, I'm gonna close the issue with the promise to end up with this list ASAP!
Thanks!
