### ISSUE TITLE
Use without bootstrap-icons

### ISSUE THREAD

**Issue by xvaara** [cdmoro/bootstrap-vue-3#168]
I'd be great to be able to use without bootstrap-icons, since unplugin-icons with vite (or other bundlers) is so good at only including used icons.

**Comment by cdmoro** [comment]
I agree we shouldn't import all icons, is pointless. I like the way that BootstrapVue team implemented it. They run a script that generates all the icons, I don't know the cost of replicating that behavior in our library.

**Comment by zoranpopovic** [comment]
unplugin-icons really shines when you use it with auto-import: https://github.com/antfu/unplugin-icons#auto-importing 
After using that setup, which works in vue2 and vue3, it's hard to think that BootstrapVue's or any other approach makes sense, especially considering that all collections  (not just BS) are just one kebab string away from being in your app.  For this reason, I imagine that bootstrap-icons are at the very bottom of the list of things people want out of this library.
