### ISSUE TITLE
Please document how to install & get started

### ISSUE THREAD

**Issue by mariusa** [cdmoro/bootstrap-vue-3#18]
Hi, thanks for this project!

How can one get started? I'd assume something like this?
```
npm i --save bootstrap-vue-3
# this will also install bootstrap
```
in main.js/ts, add
```
import ??
import 'bootstrap/scss/bootstrap.scss'
```

Shouldn't `bootstrap` be listed in `dependencies` section in package.json, so it's also installed & available in production, rather than `devDependencies` ?

**Comment by coolsam726** [comment]
From the look of things, seems like the project assumes you have installed bootstrap globally (both javascript and css). @cdmoro correct me if I am wrong. Then based on what we have in `main.ts`, the following setup would suffice.

```ts
import { createApp } from 'vue'
import BootstrapVue from 'bootstrap-vue-3';

// Optional, you can as well include your bootstrap bundles via CDN which will avail the `bootstrap` object globally
import 'bootstrap'
// Optional, you can also include this via CDN or import it separately in your sass file.
import 'bootstrap/dist/css/bootstrap.min.css'
// import './styles/styles.css';

const app = createApp(App);
app.use(BootstrapVue);
app.mount('#app');
```

I hope that helps you to get started, but I agree, a Getting Started section would be crucial at this point to help people start doing beta tests.

**Comment by mariusa** [comment]
Thanks!

> From the look of things, seems like the project assumes you have installed bootstrap globally 

Wouldn't be best to put bootstrap in bootstrap-vue-3's package.json dependencies? Since it can't be used without it anyway.

**Comment by coolsam726** [comment]
> Wouldn't be best to put bootstrap in bootstrap-vue-3's package.json dependencies? Since it can't be used without it anyway.

I tend to agree with this too. Currently it seems to be included as a `devDependency`, thought it would make more sense including it as a `dependency`. However this raises the question: What about those who prefer including bootstrap via CDN instead of building it as a module?

**Comment by cdmoro** [comment]
The install section is already online! :smiley: 
https://cdmoro.github.io/bootstrap-vue-3/getting-started/#install

also, we've moved the bootstrap package to the dependencies list

**Comment by mariusa** [comment]
> we've moved the bootstrap package to the dependencies list

Note that it's not in dependencies now. It's only in devDependencies, moved there after 0.0.1 release:
https://github.com/cdmoro/bootstrap-vue-3/blob/main/package.json

Would you please move bootstrap* back to dependencies, so it's installed automatically by adding only `bootstrap-vue-3` to one's project package.json  ?

**Comment by mariusa** [comment]
Also, where are the docs? Not present at https://github.com/cdmoro/bootstrap-vue-3/tree/main/docs/getting-started

I'm trying to send a PR to fix 
```import 'bootstrap-vue-3/dist/css/bootstrap-vue-3.css'``` (doesn't work)
to
```import 'bootstrap-vue-3/dist/bootstrap-vue-3.css'```
