### ISSUE TITLE
[Vue warn]: Invalid VNode type: Symbol(Comment) (symbol) with vue 3.2.0-beta.7

### ISSUE THREAD

**Issue by mariusa** [cdmoro/bootstrap-vue-3#21]
Hi,

```
<b-card>
test
</b-card>
```

gives

```
[Vue warn]: resolveComponent can only be used in render() or setup().
warn @ bootstrap-vue-3.js?v=bcb08cc3:1059
resolveAsset @ bootstrap-vue-3.js?v=bcb08cc3:4868
resolveDynamicComponent @ bootstrap-vue-3.js?v=bcb08cc3:4841
BCardvue_type_template_id_57ef5384_render @ bootstrap-vue-3.js?v=bcb08cc3:16802
renderComponentRoot @ chunk-LM6U7U6R.js?v=bcb08cc3:1730
...

[Vue warn]: Invalid VNode type: Symbol(Comment) (symbol)  at <BCard> 
```

The card is rendered, with with no content.

**Comment by Geoffrey-D** [comment]
I can't reproduce this issue. 

Here is the HTML generated by your code:

`<div class="card-body">test</div>`

**Comment by mariusa** [comment]
Right, I see it's working on a fresh new project. Sorry, will investigate deeper.

**Comment by mariusa** [comment]
FYI found the issue:
https://github.com/vuejs/vue-next/issues/4260

**Comment by mariusa** [comment]
Vue closed the issue :( 
I'm using other libraries too, but this happens only with bootstrap-vue-3, so maybe it's related to something in this library? They say error cause is vue being loaded 2 times.

**Comment by cdmoro** [comment]
I'm going to reopen the issue until we figure out what happens with the warning

**Comment by mariusa** [comment]
Thank you! Here's a minimal repo: https://github.com/mariusa/vue32-error

**Comment by mariusa** [comment]
More info from Vue:
Your problem is with bootstrap-vue-3. have a look at it in your node_modules folder. it has its own node_modules subfolder, containing Vue 3.1.5

The reason for this is that this package declares Vue as a dependency (which should rather be a optional peerDependency) combined with the fact that 3.2-beta isn't the latest version - it's no the next tag.

This would have to be resolved in that package.

**Comment by cdmoro** [comment]
I don't get it, it's necessary to move Vue to peerDependency list or update Vue to 3.2?

**Comment by mariusa** [comment]
vue should be moved to devDependencies or peerDependencies. Here's how another vue3 library declares vue:
https://github.com/yaminncco/vue-sidebar-menu/blob/next/package.json
