### ISSUE TITLE
b-modal class attributes issues

### ISSUE THREAD

**Issue by atlasmercan** [cdmoro/bootstrap-vue-3#214]
b-modal class attributes not applied to component . it gives a warning " **Extraneous non-props attributes (dialog-class) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.** "

![chrome_orRHMNFOVZ](https://user-images.githubusercontent.com/67555436/140277680-2e6df7ad-df8b-4c2b-8530-38afa3a00055.png)

**Comment by axelthat2** [comment]
I think this is solved in https://github.com/cdmoro/bootstrap-vue-3/pull/200

**Comment by atlasmercan** [comment]
i will check it thanks ...

**Comment by cdmoro** [comment]
Any news about this?

**Comment by cdmoro** [comment]
Hello?

**Comment by axelthat2** [comment]
Are you talking to me? If so then I am sure it’s solved already.

**Comment by cdmoro** [comment]
No no, I was talking to @atlasmercan :smile: but thanks for the response, I'm gonna close the issue for now.
