### ISSUE TITLE
Request: nightly build

### ISSUE THREAD

**Issue by 82amp** [cdmoro/bootstrap-vue-3#220]
Current codebase is substantially different from released package. 
Would it be worthwhile creating a nightly/unstable build to allow developers to consume latest code?

It could be done on the same NPM package name with a version suffix (0.0.6-nightly.2021.11.08.{commitId}), or with a different package (e.g. bootstrap-vue-3-nightly)

**Comment by cdmoro** [comment]
I found [this](http://jbavari.github.io/blog/2015/10/16/using-npm-tags/). The use of NPM tags makes really simple publish beta releases: `npm publish --tag beta`.

If you want to use the beta version you simply execute this command: `npm install bootstrap-vue-3@beta --save`.

**Comment by cdmoro** [comment]
Hello there, please try running `npm install bootstrap-vue-3@develop --save` and check if you have the last version. I've just published it from the `develop` branch.

**Comment by Radouch** [comment]
Hello, I just tried it. `package.json` reports installed version 0.0.6 and the code of this package in `node_modules` seems to be up-to-date.

**Comment by 82amp** [comment]
@cdmoro 0.0.6@develop works. Can this be set up to be a nightly/per commit build?

**Comment by cdmoro** [comment]
I think it could be possible, let me check
