### ISSUE TITLE
BFormCheckbox value type Number

### ISSUE THREAD

**Issue by antonA418** [cdmoro/bootstrap-vue-3#224]
**BFormCheckbox** component have only [Boolean, String, Array, Object] as **value** type
Would you please add also Number?
like [bootstrap-vue](https://bootstrap-vue.org/docs/components/form-checkbox#comp-ref-b-form-checkbox-props)

**Comment by jclijmans** [comment]
Should be fixed by #198

**Comment by cdmoro** [comment]
Try our development version `install bootstrap-vue-3@develop --save` in order to get the edge features 😀

**Comment by cdmoro** [comment]
@antonA418 do we have any news about this? could you test it in the development version? Please, let me know if it's resolved so I can close the issue

**Comment by flvportafolio** [comment]
I just tested that case and it is solved.
