### ISSUE TITLE
Multiple BModals, overlays not correct in 0.25.0

### ISSUE THREAD

**Issue by amokrunnr** [cdmoro/bootstrap-vue-3#2261]
### Describe the bug

After the 0.25 update, the background overlay isn't showing above lower-level modals.
![image](https://github.com/user-attachments/assets/14f7f95e-6f5a-4f67-9e40-84f7416f7cee)

This can be seen in the docs site if you open multiple modals. The top modal is not putting overlay over the "lower" modal.
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/modal.html#multiple-modal-support

### Reproduction

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/modal.html#multiple-modal-support

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by suzumejakku** [comment]
There seems to also be a problem with the scrollbar of the page from which the modals are opened. Is this somehow linked to this issue ? On the same doc page, try the following scenario:

1. Click on the "Open First Modal" button => the first modal opens; the vertical scrollbar of the main page behind the modal disappears (I guess this is a correct behavior ?)
2. Click on the "Open Second Modal" button => the second modal opens
3. Close the second modal by clicking "OK" or the close button => all modals get closed, but the scrollbar on the main page is still hidden and we cannot scroll anymore
4. Click again on the "Open First Modal" button => the first modal opens
5. Close the first modal by clicking "OK" or the close button => the first modal gets closed, and the scrollbar reappears, allowing the user to scroll the main page.

**Comment by xvaara** [comment]
Yes, it's something to do with the stacking and then scroll fix I made. Seem that the no-stacking messes it up I guess. I'll figure it out.

**Comment by xvaara** [comment]
@suzumejakku should be fixed now in the linked PR
