### ISSUE TITLE
b-table: Template data item shows {{items}} and I think it should be {{item}}

### ISSUE THREAD

**Issue by ebley** [cdmoro/bootstrap-vue-3#228]
So in the code below- see where I have {{data}} to look at it? When we look at it it has {value: .... , items:} but I think it should be {value:... and item:...} (ellipses is just to help it read easier).  I also think it should include index so it should be {value:..., item: ... , index: ...} 

I did dump {{data}} below the html
  
  <b-table v-if="datalist.length > 0" striped hover :items="datalist">
     <template #cell(expired)="data">
        <span class="badge badge-pill badge-success" v-if="data.value==0">{{data.value}}</span>
        <span class="badge badge-pill badge-danger" v-if="data.value > 0">{{data.value}}</span>
        {{data}}
      </template>
 </b-table>

Here is a dump of the {{data}} variable from above. Note it has items and I think it should be item and its also missing index.
{ "value": 0, "items": [ { "name": "DwfEnkAdvSteel", "inTime": "2021-11-15 11:58:58.000", "status": "76", "alarmTime": "2021-11-15 12:07:18", "expectedCheckinSeconds": 500, "expired": 0, "emailsToAlertCsv": "bob@me.com", "snoozeRepeatSeconds": 3600, "alarmCount": 0 }, { "name": "EnkApdBBackup", "inTime": "2021-11-14 07:25:09.000", "status": "true", "alarmTime": "2021-11-15 07:25:09", "expectedCheckinSeconds": 86400, "expired": 1, "emailsToAlertCsv": "bob@me.com", "snoozeRepeatSeconds": 3600, "alarmCount": 1 } ] }

**Comment by cdmoro** [comment]
Are you using the development version or the stable version?

**Comment by ebley** [comment]
ummmm... just npm install bootstrap-vue-3 . I think I am answering your question

**Comment by protomors** [comment]
"item" and "index" were added to template only recently. You can either wait for release or use development branch (installed as "npm install bootstrap-vue-3@develop").
And about "items"... It is indeed contains data for all items in the table. I am not sure myself, why it can be needed in cell template. But it was already there when I changed BTable so I left it.
