### ISSUE TITLE
versioning schema: please use 0.x.x

### ISSUE THREAD

**Issue by mariusa** [cdmoro/bootstrap-vue-3#23]
As this project evolves rapidly, I'd like to always use the latest version without changing my project package.json every time. One can use
```
"bootstrap-vue-3": "0.x.x"
```
which will always reference the latest version.

The current naming scheme '0.x.x-alpha.2' breaks this. 
Would you please use only '0.0.3', '0.0.4'... , without "alpha"? 

Thanks!

**Comment by cdmoro** [comment]
Hello there, since this project is in alpha state, I follow this [point](https://semver.org/#spec-item-9) of the semantic versioning. It seems a valid version scheme. Do you believe that we should utilize 0.0.x notation?

**Comment by mariusa** [comment]
I've read some more about it and it is indeed valid. Also used by vue. Although, personally I think anything 0.x.x is alpha/beta.

I was just looking for a pattern that will always install the latest version. This seems to work: `>0.0.1-alpha || >0.0.1`

Thanks for considering!
