### ISSUE TITLE
b-modal: if okTitle / cancelTitle are given as empty strings, hide buttons

### ISSUE THREAD

**Issue by mariusa** [cdmoro/bootstrap-vue-3#234]
okTitle / cancelTitle might not be present, in this case they have the default values.

I also need to hide one of them, sometimes.

If if okTitle / cancelTitle are given as empty strings, please hide the buttons.
a `v-if` could be added here? Hoping the default value isn't set when given as empty strings, only when undefined.
https://github.com/cdmoro/bootstrap-vue-3/blob/19513da03986afa4da03198dfaa15f828d7749c5/src/components/BModal.vue#L40

**Comment by flvportafolio** [comment]
meanwhile you can customize that part with `hide-footer`

example:
```html
<b-modal id="exampleModal" hide-footer v-model="showModal" size="xl" title="Modal title">
  ...
</b-modal>
```

**Comment by cdmoro** [comment]
I don't know, if you need to hide one of the buttons you could use `ok-only` prop. For me, if you pass an empty string is a "valid" value, you have to worry about what type of variables you use.

**Comment by mariusa** [comment]
Thanks, will use `okOnly`
