### ISSUE TITLE
[feature request] please add Toast component

### ISSUE THREAD

**Issue by mariusa** [cdmoro/bootstrap-vue-3#241]
[toast](https://getbootstrap.com/docs/5.0/components/toasts/)

Would be quite useful to show notifications. Thank you!

I'm not sure how Bootstrap would work though, I see it has markup to show notification(s).
Currently using https://www.primefaces.org/primevue/showcase/#/toast
and display notifications via JavaScript (not caring about the HTML markup).

**Comment by aceofwings** [comment]
toast is in development, ive been working on it but maybe cdmoro can say more to this.

**Comment by mariusa** [comment]
Added via https://github.com/cdmoro/bootstrap-vue-3/pull/277
