### ISSUE TITLE
Can't get property option working of component <b-form-select> 

### ISSUE THREAD

**Issue by GerardProgrammeert** [cdmoro/bootstrap-vue-3#258]
I like your plugin since I use the latest version of vue and bootstrap. 

However I'm having trouble with the property options of the the component <b-form-select :options>
The values of the options are shown in the code but not text of the options. 
So in the browser there is a empty select dropdown box. See screenshot

I'm using version  
"vue": "^3.0.0",
"bootstrap-vue-3": "^0.1.0",

This is my vue script
[vue_script_b_form_select.txt](https://github.com/cdmoro/bootstrap-vue-3/files/7856050/vue_script_b_form_select.txt)

This is the result in the browser 
![screenshot_form_b_form_select](https://user-images.githubusercontent.com/48645416/149176222-23b1377d-86a8-4f78-be1c-43b4552022f6.png)

I don't know what I'm doning wrong.

**Comment by sfe-efficy** [comment]
This issue is duplicated with https://github.com/cdmoro/bootstrap-vue-3/issues/249

**Comment by mariusa** [comment]
#249
