### ISSUE TITLE
The id of the modal window is lost

### ISSUE THREAD

**Issue by stefanpolishchuk** [cdmoro/bootstrap-vue-3#259]
When I add a modal window component, nothing happens when the button is clicked. In the code, you can see that the button does not have the modal ID specified. I tried to manually substitute the modal window ID and it helped.

Component code:

```
<div>
  <b-button v-b-modal.my-modal>Show Modal</b-button>
  <b-button v-b-modal="my-modal">Show Modal</b-button>
  <b-modal id="my-modal">Hello From My Modal!</b-modal>
</div>
```

![image](https://user-images.githubusercontent.com/9572728/149340188-3ab28b1d-65ee-43e3-8857-89490b49838b.png)

**Comment by aleksvaganoff** [comment]
It seems the issue with BModal directive. There should be `binding.value` instead of `binding.arg`
