### ISSUE TITLE
Please add b-form-group

### ISSUE THREAD

**Issue by mariusa** [cdmoro/bootstrap-vue-3#27]
Now that most form elements are working, please consider adding `b-form-group` too:
https://bootstrap-vue.org/docs/components/form-group

Thanks!

**Comment by atilleul** [comment]
Note that "form-group" class has been removed from Bootstrap 5 (https://getbootstrap.com/docs/5.0/migration/#forms).
Is this component still relevant or should we just use grid and utilities instead?

**Comment by cdmoro** [comment]
In fact, this is a breaking change. In the migration guide (the link that @atilleul shared), the bootstrap team recommends using their "grid and utilities instead of `.form-group`, `.form-row`, or `.form-inline`".
