### ISSUE TITLE
:to router support missing from b-dropdown-item

### ISSUE THREAD

**Issue by kris-sum** [cdmoro/bootstrap-vue-3#272]
the 'to' property seems to be missing / not working on lots of components, despite the documentation mentioning it:

https://cdmoro.github.io/bootstrap-vue-3/components/Dropdown.html#b-dropdown-item 
> "The <b-dropdown-item> is typically used to create a navigation link inside your menu. Use either the **href** prop or the **to** prop (for router link support) to generate the appropriate navigation link."

I've tried supplying "to" but nothing is rendered, and it doesn't look like it's in the sourcecode.

**Comment by xvaara** [comment]
I've created a pull request to add the support.

in the meantime you can use router-link directly:
```
<router-link
  v-slot="{ href, navigate, isActive }"
  to="/test"
  custom
>
  <b-dropdown-item :active="isActive" :href="href" @click="navigate">
    test
  </b-dropdown-item>
</router-link>
```

**Comment by mariusa** [comment]
Thanks @xvaara !
