### ISSUE TITLE
Nuxt3 - Accordion doesn't open after page change

### ISSUE THREAD

**Issue by duxa174** [cdmoro/bootstrap-vue-3#278]
Hi. I'm trying to use nuxt3 + bootstrap-vue-3 and ran into a problem.
The accordions stop opening after switching from the test page to the main page and back. Is there any solution?

Demo: https://stackblitz.com/edit/github-4sj1wy

UPD: I found out that 'target' is undefined
https://github.com/cdmoro/bootstrap-vue-3/blob/92a0525174793af0007b6fc48b72d0161183f824/src/directives/BToggle.ts#L55

**Comment by wobsoriano** [comment]
Just wrap it with `<ClientOnly />` component and it should work.

```html
<template>
  <div>
    <ClientOnly>
      <b-accordion>
        <b-accordion-item title="Accordion Item #1" visible>
          hello world
        </b-accordion-item>
      </b-accordion>
    </ClientOnly>
  </div>
</template>
```

**Comment by VividLemon** [comment]
Closing as this is well known, but not viable until a future release of Bootstrap
