### ISSUE TITLE
When v-model=false in BModal, the backDrop does not hide

### ISSUE THREAD

**Issue by tghkuma** [cdmoro/bootstrap-vue-3#285]
Maybe a Bootstrap bug that now needs a patch.
Bootstrap issue[#33727](https://github.com/twbs/bootstrap/issues/33727)

**Comment by tghkuma** [comment]
In the parent component. The problem was that it was controlled by v-if as in the Nuxt 3 [Dynamic Import](https://v3.nuxtjs.org/docs/directory-structure/components#dynamic-imports) sample.

It seems that the component disappeared during the hidden process and the background remained.

App.vue
```
<template>
    <b-button @click="showModal = !showModal">Modal Toggle</b-button>
    <ErrorModal v-model="showModal" v-if="showModal" />
<!--
    ↓success
    <ErrorModal v-model="showModal" />
-->
</template>

<script lang="ts" setup>
import BootstrapVue3 from 'bootstrap-vue-3'
import {ref} from "vue";

useNuxtApp().vueApp.use(BootstrapVue3)
const showModal = ref(false)
</script>
```

ErrorModal.vue
```
<template>
  <b-modal v-model="childShowModal">
    <b-button @click="childShowModal = false">Modal Close</b-button>
  </b-modal>
</template>

<script lang="ts" setup>
interface Props {
  modelValue?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: false,
})

const emit = defineEmits(['update:modelValue'])
const childShowModal = computed({
  get: () => props.modelValue,
  set: (value) => {
    emit('update:modelValue', value)
  },
})
</script>
```

**Comment by IARI** [comment]
Sorry for posting - I know this repo is deprecated.
Still I don't understand why the issue was closed. The problem appears to persists for me if the parent component always is rendered.
