### ISSUE TITLE
Vite build error: rollup could not resolve re-exports

### ISSUE THREAD

**Issue by Oni07R** [cdmoro/bootstrap-vue-3#296]
I am having a big issue with "vite build" (just "vite", for dev testing works flawlessly). The problem is in two files:

- boostrap-vue-3/src/types/index.ts
the problem is in this import
```
import VerticalAlign from './VerticalAlign'

'VerticalAlign' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

```
- bootstrap-vue-3/src/types/container.ts
the problem lies in all exports
```
export { default as Alignment } from './Alignment'
export { default as Animation } from './Animation'
export { default as BootstrapVueOptions } from './BootstrapVueOptions'
export { default as BreadcrumbItem } from './BreadcrumbItem'
export { default as Breakpoint } from './Breakpoint'
export { default as ButtonVariant } from './ButtonVariant'
export { default as ColorVariant } from './ColorVariant'
export { default as InputSize } from './InputSize'
export { default as InputType } from './InputType'
export { default as LinkTarget } from './LinkTarget'
export { default as Pagination } from './Pagination'
export { default as PaginationPage } from './PaginationPage'
export { default as RadioOption } from './RadioOption'
export { default as Size } from './Size'
export { default as SpinnerType } from './SpinnerType'
export { default as TableField } from './TableField'
export { default as TableItem } from './TableItem'
export { default as TextColorVariant } from './TextColorVariant'
export { default as VerticalAlign } from './VerticalAlign'

'VerticalAlign' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.
```

The VScode/lint error can be suppressed by adding `isolatedModules: false` to tsconfig.json but rollup still breaks during build.

In both files I solved the problem by adding "type" to the import/export, building the web app on my PC and then copying build files on the web server.
This however breaks the CI/CD pipeline on GitLab, which would be too cumbersome to adapt to this workaround.

**Comment by mariusa** [comment]
Hi, I don't know enough to understand the proper fix. Would you be able to check bestpractices on other Vue3 libraries and submit a PR with adjustments?

**Comment by Oni07R** [comment]
Honestly, I don't feel qualified enough for a PR request but let me try :P

**Comment by Oni07R** [comment]
I see you have merged the pull request, this issue can be closed.
Is there an ETA for the next npm release with the fix?

**Comment by mariusa** [comment]
> Is there an ETA for the next npm release with the fix?

Just made a new release :)
