### ISSUE TITLE
Roadmap to a production ready version?

### ISSUE THREAD

**Issue by stam** [cdmoro/bootstrap-vue-3#299]
Hey Carlos, first of all thank you for your hard work on bootstrap-vue-3.

In the documentation you mention that this library is not production ready and still is in alpha version.
Is there a list of components/features/requirements that are still needed for this library to reach a production version?

I would like to upgrade the product I work on to this repo, and want to contribute to this library in order to reach a production ready version

**Comment by mariusa** [comment]
Hi & thanks,

Feel free to contribute with whatever you're missing from your project. We could also use help on
1. building docs (having an error now; might be useful to migrate from vuepress to vitepress)
2. reviewing all form components (maybe comparing with bootsrap-vue) and adding what's missing

Also see https://github.com/cdmoro/bootstrap-vue-3/projects/1
