### ISSUE TITLE
Please add b-form-radio-group / b-form-checkbox-group 

### ISSUE THREAD

**Issue by mariusa** [cdmoro/bootstrap-vue-3#30]
similar to https://bootstrap-vue.org/docs/components/form-radio

**Comment by Geoffrey-D** [comment]
Hey @mariusa,

I have implemented the "BFormCheckboxGroup" component in the pull request https://github.com/cdmoro/bootstrap-vue-3/pull/64.

There are probably some fine tuning to be done but the basic features are working.

Let me know if you find any issues with that component :)

**Comment by mariusa** [comment]
Excellent, Geoffrey! Thanks so much!
I've tested your fork with a couple of use cases and it works great :grin:   

Could you also do the `b-form-radio-group` ?

**Comment by Geoffrey-D** [comment]
Yes that's planned :)

**Comment by Geoffrey-D** [comment]
b-form-radio-group is waiting to be merged in https://github.com/cdmoro/bootstrap-vue-3/pull/67 :)

**Comment by mariusa** [comment]
Great news!

Carlos, would you please push a new release afterwards too? There have been
quite some changes. We also need to test vite build.

Wishing you a great weekend :)

**Comment by cdmoro** [comment]
I've published a new version: 0.0.2 :smile:

**Comment by mariusa** [comment]
`b-form-radio-group` and `b-form-checkbox-group` work great in 0.0.3, thanks so much!

**Comment by Geoffrey-D** [comment]
you are welcome! Thank you for the feedback, it's very motivating :)
