### ISSUE TITLE
docs build error: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by mariusa** [cdmoro/bootstrap-vue-3#301]
Tracking here. Fixes are welcome. Maybe migrate from vuepress to vitepress 

```
# build library
npm run build

# docs
cd docs
npm install
cd ..
npm run docs:build

# navigate into the build output directory
cd docs/.vuepress/dist
```

gives
```
 Compiling with vite - done
✖ Rendering pages - failed
ReferenceError: document is not defined
    at enableDismissTrigger (/home/marius/work/bootstrap-vue-3/docs/node_modules/bootstrap/dist/js/bootstrap.js:761:21)
    at /home/marius/work/bootstrap-vue-3/docs/node_modules/bootstrap/dist/js/bootstrap.js:856:3
    at /home/marius/work/bootstrap-vue-3/docs/node_modules/bootstrap/dist/js/bootstrap.js:7:83
    at Object.<anonymous> (/home/marius/work/bootstrap-vue-3/docs/node_modules/bootstrap/dist/js/bootstrap.js:10:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by cdmoro** [comment]
This type of error happens because bootstrap is not SSR friendly. Every time you use a component you have to wrap it inside a `ClientOnly` tag. We have to check all of the markdown files if we missing something.

I'm not sure if migrating to Vitepress solves the problem. Besides, Vitepress is less customizable than Vuepress.

**Comment by aceofwings** [comment]
Remove usetoast from toast.md . Even though it’s wrapped in client only the build includes it .

**Comment by cdmoro** [comment]
Maybe we should use another tool to publish the documentation (Nuxt for example). I mean, Vuepress is great but, for example, we have to tweak the styles because of Vuepress styles, the SSR errors are not clear or are impossible to track them (document is not defined don't help much, really).

**Comment by aceofwings** [comment]
I do agree. Its that or I move some of the examples to another package and we publish eg. `@boostrap-vue-3/examples`. 
I talked to one of the vuepress maintainers and recommended Async module import or client tags(Neither which work) or configuring the build tool to cover our case. Sadly the issue has to do with the `useToast` function, even though its in a client only tag, the bundler will attempt to compile Boostrap-vue-3 directives. I say for now remove the `useToast` function rendering the examples non-functional and publish the docs.

**Comment by mariusa** [comment]
Ok, thanks for checking. Will you please send a PR?

**Comment by aceofwings** [comment]
Will do !

**Comment by mariusa** [comment]
Thanks, fixed by https://github.com/cdmoro/bootstrap-vue-3/pull/305
Newest docs are now at https://cdmoro.github.io/bootstrap-vue-3/components/
