### ISSUE TITLE
Failed to resolve component: b-card-img-lazy & b-img-lazy

### ISSUE THREAD

**Issue by Slluxx** [cdmoro/bootstrap-vue-3#302]
```
[Vue warn]: Failed to resolve component: b-card-img-lazy
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

I dont think its supposed to be like this since [its in the docs](https://cdmoro.github.io/bootstrap-vue-3/components/Card.html#lazy-loaded-images)

Same goes for "b-img-lazy"

**Comment by eugen1j** [comment]
I have the same problem even for `b-button`

**Comment by edwh** [comment]
@cdmoro Could you say what the status is of b-img-lazy?  Sorry if that's somewhere obvious, but I couldn't see it at https://cdmoro.github.io/bootstrap-vue-3/reference/parityList.html.

**Comment by madbob** [comment]
Instead to add a dedicated component, I would suggest to add a boolean prop `lazy` to `b-img` and leverage the `loading="lazy"` HTML attribute [natively supported by most browsers](https://caniuse.com/loading-lazy-attr).

Far less code than reinvent it from scratch using `IntersectionObserver` (as [the BootstrapVue implementation](https://bootstrap-vue.org/docs/components/image#lazy-loaded-images)) and far easier to use (e.g. would be great to implicitely lazy load non-active images in `b-carousel`).

**Comment by mariusa** [comment]
> Instead to add a dedicated component, I would suggest to add a boolean prop lazy to b-img and leverage the loading="lazy" HTML attribute [natively supported by most browsers](https://caniuse.com/loading-lazy-attr).

Done, thanks to @VividLemon

**Comment by VividLemon** [comment]
> > Instead to add a dedicated component, I would suggest to add a boolean prop lazy to b-img and leverage the loading="lazy" HTML attribute [natively supported by most browsers](https://caniuse.com/loading-lazy-attr).
> 
> Done, thanks to @VividLemon

The intention in the future is to also include placeholder abilities. Not sure the best route. Either mimic bootstrap vue strategy of a blank img, use a slot, use vuetify strategy of lazy img with blur... but im thinking lazy img placeholder with an optional slot.
