### ISSUE TITLE
please remove bundled bootstrap-icons

### ISSUE THREAD

**Issue by mariusa** [cdmoro/bootstrap-vue-3#31]
Following up on https://github.com/cdmoro/bootstrap-vue-3/commit/6074855b675cbee6a78279f089c22063fb345afa

I'm not sure why this library should provide bootstrap icons custom support. Bootstrap doesn't require bootstrap-icons. Bootstrap includes some required svgs, eg the arrow down on form-select.
An alternative library, bootstrap-icons-vue, could be provided for the folks wanting custom support for bootstrap icons.

One can use  bootstrap icons, font awesome, primevue icons, etc, all with the standard way: 
1. link to CDN css
2. use `<i class="fa fa-gear"></i>` (all icons libraries have the same syntax).

By using bootstrap, I shouldn't be forced to include bootstrap icons custom support.

**Comment by cdmoro** [comment]
You are right! In the next version, I'm going to suppress the BIcon component temporarily. However, I think we should provide some bootstrap-icons support, but in a different way (like BootstrapVue).
I didn't know about `bootstrap-icons-vue`, this could be a good alternative indeed.

**Comment by mariusa** [comment]
This will also solve https://github.com/cdmoro/bootstrap-vue-3/issues/35

Would be great to have this done ASAP, since it's simple, and push a new release with the latest fixes. Thanks!

**Comment by mariusa** [comment]
Thanks! Note there are still 2 places referencing this
https://github.com/cdmoro/bootstrap-vue-3/search?q=b-icon

`b-avatar` now gives an error. Please remove from those places too.

**Comment by cdmoro** [comment]
Done!
