### ISSUE TITLE
Possibly outdated Vue dependency in documentation

### ISSUE THREAD

**Issue by PikaBlue107** [cdmoro/bootstrap-vue-3#312]
## Summary

This project reports that it depends on vue ^3.0.x, but missing imports seem to imply that it instead depends on vue ^3.2.x.

It could very easily be something I've misunderstood or misused, as I'm very inexperienced in web app development.

Could someone more experienced than this college undergrad senior verify this bug, and if verified, document the corrected dependency?

## Details

When trying to run an app with dependency `"vue": "^3.0.x"` as listed on this project's [documentation](https://cdmoro.github.io/bootstrap-vue-3/getting-started/#requisites), I get the following export warnings in the npm console:

```npm
 WARNING  Compiled with 6 warnings

 warning  in ./node_modules/bootstrap-vue-3/dist/bootstrap-vue-3.es.js

"export 'createElementBlock' was not found in 'vue'

 warning  in ./node_modules/bootstrap-vue-3/dist/bootstrap-vue-3.es.js

"export 'createElementVNode' was not found in 'vue'

 warning  in ./node_modules/bootstrap-vue-3/dist/bootstrap-vue-3.es.js

"export 'guardReactiveProps' was not found in 'vue'

 warning  in ./node_modules/bootstrap-vue-3/dist/bootstrap-vue-3.es.js

"export 'normalizeClass' was not found in 'vue'

 warning  in ./node_modules/bootstrap-vue-3/dist/bootstrap-vue-3.es.js

"export 'normalizeProps' was not found in 'vue'

 warning  in ./node_modules/
```

While this error is occurring, if I try to import this module as directed (with no other code whatsoever related to BootstrapVue3):
```node
import BootstrapVue3 from 'bootstrap-vue-3';
```
then my app crashes upon load with an error about the inaccessible `createElementVNode`
(specifically: `bootstrap-vue-3.es.js?b80d:1599 Uncaught TypeError: Object(...) is not a function`).

This same behavior occurs with `"vue": "^3.1.x"`, but **is fixed by upgrading to `"vue": "^3.2.x"`**

**Comment by PikaBlue107** [comment]
of course, immediately after posting this, I noticed that your `package.json` indeed lists Vue 3.2 as a dev dependency, which seems to confirm my understanding.

https://github.com/cdmoro/bootstrap-vue-3/blob/4ee50a9a7256621bea3e029ad65a57ec3f962ddf/package.json#L73

Thus the docs seems to be the main problem.

As for enforcing v3.2: I'm still fairly new to `npm` as well, but is there a compelling reason why Vue ^3.2.31 isn't listed as a peer dependency? I apologize if that's a novice question / was discussed elsewhere; I haven't been able to find an answer myself.

**Comment by mariusa** [comment]
> is there a compelling reason why Vue ^3.2.31 isn't listed as a peer dependency?

There are lots of vue* / @vue packages in "devDependencies". From looking at other libs, I see these are in "devDependencies", not peer.

**Comment by mariusa** [comment]
I've updated docs at https://github.com/cdmoro/bootstrap-vue-3/tree/main/docs/getting-started
Site will be updated with the next refresh
