### ISSUE TITLE
<b-dropdown> direction not working

### ISSUE THREAD

**Issue by SegopotsoMakhutja** [cdmoro/bootstrap-vue-3#319]
Hi there,

Direction of the dropdown not working, I'm trying to have the dropdown menu open at the top.

using 
"vue" : "3.2.30"
"bootstrap-vue-3" : "0.1.0"

```
<b-dropdown id="dropdown-dropup" dropup text="Drop-Up">
   ...
</b-dropdown>
```

**Comment by VividLemon** [comment]
Code appears to be correct. Reopen if it is still an issue.

**Comment by alexdohm** [comment]
@VividLemon i'm having the same issue, but with BNavItemDropdown. the direction props do not work, and by looking at the inspector, it seems like the props are not being applied to the element
