### ISSUE TITLE
ref is broken on form inputs

### ISSUE THREAD

**Issue by mariusa** [cdmoro/bootstrap-vue-3#32]
This works fine on a regular HTML input, as in the given example: 
https://stackoverflow.com/questions/66868775/how-to-set-initial-focus-on-input-field-on-page-load-with-vuejs-3-using-composi

But using 
```
<b-form-input ref="filter" ></b-form-input>
```

doesn't work.

Looks like `ref` is always overwritten with `input`, instead of user provided value:
https://github.com/cdmoro/bootstrap-vue-3/blob/b258f565b032088afe87651141afebeeedee5931/src/components/BFormInput.vue#L4

https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGlucHV0IC8+XG4gIDxpbnB1dCByZWY9XCJmaWx0ZXJcIiAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmNvbnN0IG1zZyA9ICdIZWxsbyBXb3JsZCEnXG5cbmltcG9ydCB7IHJlZiwgb25Nb3VudGVkLCBuZXh0VGljayB9IGZyb20gJ3Z1ZSc7XG5cbiAgY29uc3QgZmlsdGVyID0gcmVmKG51bGwpO1xuXG4gIG9uTW91bnRlZCgoKSA9PiB7XG4gICAgbmV4dFRpY2soKCkgPT4ge1xuICAgICAgZmlsdGVyLnZhbHVlLmZvY3VzKCk7XG4gICAgfSk7XG4gIH0pO1xuXG48L3NjcmlwdD4ifQ==

**Comment by mike-kelly** [comment]
I have the same issue with version 0.9.14.
When trying to set the focus on a <b-form-input> field via its ref I get the error message `input.value.focus is not a function`
It works fine with a normal <input /> field.
