### ISSUE TITLE
BootstrapVue.d.ts problem

### ISSUE THREAD

**Issue by letrhee** [cdmoro/bootstrap-vue-3#326]
There is a problem with using exported functions (eg `useToast()`) because BootstrapVue.d.ts has no content.

It would be nice if there is a well-generated d.ts, or something like the following:

```ts
export * from './BootstrapVue';
import { BootstrapVue3 } from './BootstrapVue';
export default BootstrapVue3;
```

**Comment by letrhee** [comment]
@extrem7, A workaround can be to replace the above mentioned contents in the `node_modules/bootstrap-vue-3/src/BootstrapVue.d.ts` file.

For me, checking the contents of bv3 every time in `tsc --noEmit` is a bit annoying.

**Comment by messenjer** [comment]
Hello,

I made a pull request to generate the *.d.ts files from .ts or .vue source https://github.com/cdmoro/bootstrap-vue-3/pull/352 

It's possible for you to test it ?

- git clone the repo with the branch 
- `npm install`
- `npm build`
- `npm pack` --> will build a file `bootstrap-vue-3-0.1.10.tgz`

And install the package in your project

- `npm install {replace-with-the-correct-path}/bootstrap-vue-3-0.1.10.tgz

Regards

Mathieu

**Comment by extrem7** [comment]
![image](https://user-images.githubusercontent.com/24792876/162476215-733fd253-2461-402c-890e-4f75e5d85b8e.png)
![image](https://user-images.githubusercontent.com/24792876/162476314-581139f5-a5f8-4886-91d8-74e942d21370.png)

Perfect!

**Comment by letrhee** [comment]
Works perfectly! thank you!!
