### ISSUE TITLE
BootstrapVue plugin options

### ISSUE THREAD

**Issue by makroxyz** [cdmoro/bootstrap-vue-3#328]
Hi!
I'm trying to globally set some props in this way without success.

```js
app.use(BootstrapVue3, {
    BModal: {
        cancelTitle: 'MyLabel'
    }
})
```

Am I wrong or is it a missing feature?

**Comment by cdmoro** [comment]
Yes, sorry about that but we haven't developed that feature yet.

**Comment by makroxyz** [comment]
OK! I want to be sure that I did it right!

Anyway you're doing an amazing job!
I have a big application, and I'm considering to migrate to vue3/bv3 as soon as tables will be available

**Comment by makroxyz** [comment]
hi is this feature available now?

**Comment by makroxyz** [comment]
@aceofwings could you re-open this issue please?
It's a very important feature to have... 

```
app.use(BootstrapVue3, {
    BModal: {
        cancelTitle: 'Annulla',
    },
    BLink: {
        routerComponentName: 'router-link' // I'm using inertiajs so this component is a wrapper for inertia's Link object
   }
})
```
