### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by bobaoapae** [cdmoro/bootstrap-vue-3#33]
> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: bootstrap-vue-3@0.0.1-alpha.3
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.32.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.13
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"~4.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\jvbor\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jvbor\AppData\Local\npm-cache\_logs\2021-08-12T17_36_46_149Z-debug.log

Seems to be a issue with incompatible version of cli-serve and eslint, eslint 7 it's only supported on cli-service beta 5

**Comment by mariusa** [comment]
vue-cli isn't required anymore, since vitejs works out of the box now and
it's faster. I propose to remove it, I don't see any advantage?
(Already switched my projects to vite)


Marius

**Comment by bobaoapae** [comment]
I want to try do develop some things missing on this component for i can use in my project migrating to vue3 but i can't start due to error on run npm install

**Comment by cdmoro** [comment]
Please, try using `yarn` to install the dependencies.

**Comment by bobaoapae** [comment]
yarn install work, but will be nice to work with npm install to, i never used yarn before

**Comment by mariusa** [comment]
@cdmoro Would you agree to remove vue-cli support? This would reduce dependencies (webpack is huge) and also solve this bug. Vitejs is the preferred way to run & build Vue 3 apps and it already works fine with bootstrap-vue-3 (I added the support). It's much faster too.

I can send a PR if you agree.

**Comment by cdmoro** [comment]
The thing is we use vue-cli to build this project as a library.

With Vite this process has to be done manually, as described [here](https://vitejs.dev/guide/build.html#library-mode). Feel free to make a PR, but with this in mind, please.

**Comment by mariusa** [comment]
> we use vue-cli to build this project as a library.

by running `npm run build-cli` ?

(note, that gives `Syntax Error: Thread Loader (Worker 1) .eslintrc.js:        Environment key "jest/globals" is unknown`)

I've made the PR, `npm run build` and `yarn run build` work fine. Note that instead of `dist/common.js` file, a `dist/es.js` file is now built. `umd` file remains.

**Comment by mariusa** [comment]
FYI node_modules/ dropped from 901 to 636 packages now :D
