### ISSUE TITLE
Btable

### ISSUE THREAD

**Issue by nagisaando** [cdmoro/bootstrap-vue-3#336]
Sorry if this one has already answered somewhere but could not find a clear answer.

Is b-table available already? I see it exists in main branch but it does not render anything when but just text.

<img width="658" alt="Screen Shot 2022-03-24 at 7 42 24 AM" src="https://user-images.githubusercontent.com/56172522/159941592-aaeb7735-5471-430e-be99-830e6094d2f9.png">

<img width="538" alt="Screen Shot 2022-03-23 at 12 41 59 PM" src="https://user-images.githubusercontent.com/56172522/159941656-299fb596-1c58-4e43-b2b0-a984aca2fce6.png">

**Comment by oselow** [comment]
Yep, same error, waiting for fix :p

**Comment by viaregio** [comment]
ditto

**Comment by aceofwings** [comment]
@nagisaando 

If you can provide your code in the markup instead of a picture that would be great

**Comment by nagisaando** [comment]
@aceofwings Hi, thank you for answering! 

This is the code, got from BootstrapVue doc https://bootstrap-vue.org/docs/components/table

````
<template>
  <div>
    <b-table :items="items"></b-table>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        items: [
          { age: 40, first_name: 'Dickerson', last_name: 'Macdonald' },
          { age: 21, first_name: 'Larsen', last_name: 'Shaw' },
          { age: 89, first_name: 'Geneva', last_name: 'Wilson' },
          { age: 38, first_name: 'Jami', last_name: 'Carney' }
        ]
      }
    }
  }
</script>
````

**Comment by aceofwings** [comment]
@nagisaando and others

A hot fix has been pushed to main and a release will be made later in the week to account for fix. 

#359
