### ISSUE TITLE
 tabs Documentation shows error

### ISSUE THREAD

**Issue by yangjrun** [cdmoro/bootstrap-vue-3#339]
https://cdmoro.github.io/bootstrap-vue-3/components/Tabs.html#dynamic-tabs-tabs-end-slot
![image](https://user-images.githubusercontent.com/31336383/160102114-a5b90c3c-4e58-4fdd-9d7f-5aef2a80c980.png)

**Comment by messenjer** [comment]
We can close it. It's fixed.
