### ISSUE TITLE
Form Checkbox: Switch does not properly slide right on checked

### ISSUE THREAD

**Issue by harunsasmaz** [cdmoro/bootstrap-vue-3#357]
I am trying to use `<b-form-checkbox switch>`. However, when I click on switch, it stops sliding right on the middle. See image [here](https://imgur.com/a/wgQI0En)

Here is my usage:

`<b-form-checkbox switch @change="change(b)" :disabled="isDisabled(b)" size="lg" v-model="b.check"></b-form-checkbox>
`
Everything works properly except css part. 

I am using `yarn dev`, i.e. `vite` to run program on localhost.  

Here is my `package.json` for versions of the dependencies. 

```
"dependencies": {
    "@dafcoe/vue-collapsible-panel": "^0.2.0",
    "@popperjs/core": "^2.11.5",
    "@tailwindcss/aspect-ratio": "^0.2.0",
    "@tailwindcss/forms": "^0.2.1",
    "@tailwindcss/typography": "^0.4.0",
    "@tailwindcss/ui": "^0.7.2",
    "bootstrap": "^5.1.3",
    "bootstrap-vue-3": "^0.1.10",
    "vue": "^3.2.32",
    "vue-router": "4",
    "yarn": "^1.22.18"
  }
```

Problem might be related to using tailwindcss together with bootstrap but I am not sure and I cannot find anything similar.

**Comment by mariusa** [comment]
Works fine in current version. Please provide a minimal reproduction, excluding tailwindcss

**Comment by panhow** [comment]
```
<template>
  <b-form-checkbox
    v-model="check"
    :value="1"
    :unchecked-value="0"
    switch
  >
    switchTest
  </b-form-checkbox>
</template>
<script setup lang="ts">
const check = ref(0)
</script>
```
@mariusa 
here is my minimal reproduction, when switch to true,  switch won't slide to right

**Comment by panhow** [comment]
ok, `making a computed value that returns based on the vmodel value.` can be help.

i will open a new issue for this problem.

thanks for reply
