### ISSUE TITLE
Programmatically access breakpoints?

### ISSUE THREAD

**Issue by edwh** [cdmoro/bootstrap-vue-3#361]
I've used a variety of hacky methods to access the currently active breakpoint from Javascript (e.g. v-b-visible).  Is there going to be a "right" way to do this in bootstrap-vue-3?  

Thanks so much to everyone working on this.

**Comment by aceofwings** [comment]
was this an original way of doing this in Bootstrap-vue?

**Comment by edwh** [comment]
I didn't find a standard built-in way of doing it in Bootstrap Vue, or raw Bootstrap, though that doesn't mean that there wasn't one.  

That might mean that we're not doing it, of course, but I want to check that I'm not missing something that everyone else knows about.

**Comment by xvaara** [comment]
there ain't one. But you can create it with yourself.

for example: https://vue3-mq.info/configure/presets.html
has preset of bootstrap default breakpoints. 

Notice that breakpoints are display rules for css and aren't "readable" (you'd have to parse the whole css file.). They can also be customised in bootstrap scss.

**Comment by edwh** [comment]
Ok.  What I did was this:

```
<template>
  <span>
    <span ref="xs" class="d-block d-sm-none" />
    <span ref="sm" class="d-none d-sm-block d-md-none" />
    <span ref="md" class="d-none d-md-block d-lg-none" />
    <span ref="lg" class="d-none d-lg-block d-xl-none" />
    <span ref="xl" class="d-none d-xl-block" />
  </span>
</template>
<script>
import ResizeObserver from 'resize-observer-polyfill'

export default {
  mounted() {
    // Spot when the elements become visible/hidden.
    const ro = new ResizeObserver(this.check)
    ;['xs', 'sm', 'md', 'lg', 'xl'].forEach(breakpoint => {
      ro.observe(this.$refs[breakpoint])
    })

    this.check()
  },
  methods: {
    check() {
      const oldBreakpoint = this.$store.getters['misc/get']('breakpoint')
      let currentBreakpoint = oldBreakpoint
      ;['xs', 'sm', 'md', 'lg', 'xl'].forEach(breakpoint => {
        if (this.$refs[breakpoint]) {
          if (getComputedStyle(this.$refs[breakpoint]).display === 'block') {
            // This breakpoint is visible and is therefore the current one.
            currentBreakpoint = breakpoint
          }
        }

        if (currentBreakpoint !== oldBreakpoint) {
          this.$store.dispatch('misc/set', {
            key: 'breakpoint',
            value: currentBreakpoint
          })
        }
      })
    }
  }
}
</script>

```

**Comment by xvaara** [comment]
oh, that is a nice way of doing it! Didn't think of that. 

the breakpoints have some differences in bootstrap5, but that could work with small changes.

**Comment by xvaara** [comment]
Just for fun I did a component and a composable for that idea:
https://stackblitz.com/edit/vitejs-vite-qbxaoh?file=src%2FApp.vue&terminal=dev

**Comment by cdmoro** [comment]
What about https://vueuse.org/core/usebreakpoints/#usebreakpoints?

**Comment by edwh** [comment]
@cdmoro That looks like the kind of thing.  Thanks.

**Comment by xvaara** [comment]
vueuse is also a good option. It's also based on predefined breakpoints: https://github.com/vueuse/vueuse/blob/main/packages/core/useBreakpoints/breakpoints.ts#L19-L25
