### ISSUE TITLE
Doc: nav component is missing

### ISSUE THREAD

**Issue by dhanyn10** [cdmoro/bootstrap-vue-3#365]
nav component is missing in reference -> component.
**BNav** already added in `src/component` but you forget to write documentation about how to use it.

**Comment by edwh** [comment]
Aren't navbar and nav separate components?

**Comment by dhanyn10** [comment]
oh, right. I usually uses navbar, not nav. from bootstrap usually the html also uses `nav` class in **navbar** component. Currently, both of them aren't documented yet. And the BNarBar isn't implemented.
So, who will open the next issues? 😃

**Comment by VividLemon** [comment]
Should be completed, though documentation may still be lacking in some areas.
