### ISSUE TITLE
Form select (using Object options) doesn't show selected option correctly

### ISSUE THREAD

**Issue by lanlegion** [cdmoro/bootstrap-vue-3#366]
When using the b-form-select component, when passing in a list of { text, value } objects, where the value is also an object, the selected option doesn't seem to update. The v-model value does properly update.

(Using compositional API)
In script setup:
```
const selected = ref({})
const options = ref([
    { text: 'foo', value: { blub: 'bar' } },
    { text: 'hi', value: { blub: 'hivalue' } },
    { text: 'foo3', value: { blub: 'bar3' } },
  ])
```

In template:
```
<b-form-select
      v-model="selected"
      text-field="text"
      :options="options"
    ></b-form-select>
```

The selected option stays displayed as 'foo' in this case.

Do tell me if/where more clarification is needed, this is my first time reporting an issue.

EDIT: I see this is a known bug. Should I close the issue? I would really appreciate a workaround!

**Comment by messenjer** [comment]
There is a pull request waiting to be reviewed, you can test it if you want https://github.com/cdmoro/bootstrap-vue-3/pull/363

**Comment by lanlegion** [comment]
> There is a pull request waiting to be reviewed, you can test it if you want #363

Thanks! I saw, and I skimmed through the code. I might test it, but I don't think we would use the forked repo in our project. I already have a (very ugly) workaround involving finding the option by name. 

I'm waiting for the developer to merge for now

**Comment by mariusa** [comment]
merged & released

**Comment by lanlegion** [comment]
> merged & released

Yes, it works! Great! Thank you. I'll close the issue.
