### ISSUE TITLE
B-toasts dont appear

### ISSUE THREAD

**Issue by CatPawns** [cdmoro/bootstrap-vue-3#371]
Toasts seems to dont work, even on the examples pages.

**Comment by aceofwings** [comment]
Please give more context or the issue will be marked closed.

**Comment by CatPawns** [comment]
I imported the toast plugin they dont apper, i checked the website with examples they dont work there too.

**Comment by aceofwings** [comment]
Examples dont work due to SSR and Vuepress build. Browser does not matter.

**Comment by aceofwings** [comment]
Closed due to inactivity and insufficient information.
