### ISSUE TITLE
The local dev server of the documentation (vuepress) and the build are not working

### ISSUE THREAD

**Issue by messenjer** [cdmoro/bootstrap-vue-3#372]
Hello,

Today I tried to run `vuepress`, and I couldn't do it.

I take the latest version of the project

```
npm install
npm run build
cd docs
npm install
npm run dev
```

Open the url http://localhost:8080/bootstrap-vue-3/ 

Error in the console.log : 

```
chunk-RTLFYRTT.js:79 Uncaught (in promise) Error: useRouteLocale() is called without provider.
    at useRouteLocale (chunk-RTLFYRTT.js:79:11)
    at setup (SearchBox.js:27:29)
```

The version of `vuepress`

```
npx vuepress -v
vuepress/core@2.0.0-beta.35 vuepress/cli@2.0.0-beta.35 darwin-x64 node-v16.13.1 
```

I think, it's linked to vuepress latest releases and breaking changes.
* https://github.com/vuepress/vuepress-next/blob/main/CHANGELOG.md

@mariusa, @cdmoro, @aceofwings ?  Can you make Vuepress work on local ? 

Mathieu

**Comment by messenjer** [comment]
I did a Pull request with the fix https://github.com/cdmoro/bootstrap-vue-3/pull/373

**Comment by mariusa** [comment]
Excellent, thanks!
