### ISSUE TITLE
Build error: "vue"' has no exported member named 'Reactive'. Did you mean 'reactive'

### ISSUE THREAD

**Issue by snmuhein** [cdmoro/bootstrap-vue-3#392]
Hello

When I try to build my vue-3 project with `npm run build` I get the following error:
```
node_modules/bootstrap-vue-3/dist/components/BToast/plugin.d.ts:1:68 - error TS2724: '"vue"' has no exported member named 'Reactive'. Did you mean 'reactive'?

1 import { Plugin, ComponentPublicInstance, VNode, Ref, ComputedRef, Reactive } from 'vue';
```

The problem seems to be introduced with bootstrap-vue-3 version 0.1.11.

**Comment by messenjer** [comment]
The type is used here https://github.com/cdmoro/bootstrap-vue-3/blob/4413fd628c1da9170c8deb97a1adeef44cbb621c/src/components/BToast/plugin.ts#L23

How do you use the Toaster ? May be we need to use import type ?

**Comment by snmuhein** [comment]
The Toaster is not at all in any template.
Here is how I use bootstrap-vue-3 in the project.

```js
// main.ts
// Import Bootstrap and BootstrapVue CSS files (order is important)
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-vue-3/dist/bootstrap-vue-3.css';

import BootstrapVue3 from 'bootstrap-vue-3';
import { createApp, h } from 'vue';

import App from './App.vue';
import router from './router';

const app = createApp({
  render: () => h(App),
});

app.use(BootstrapVue3);
app.use(router);
app.mount('#app');
```

**Comment by snmuhein** [comment]
I can suppress the error by adding "skipLibCheck": true to the tsconfig.json

```json
// tsconfig.json
{
  "compilerOptions": {
    // other settings
    "skipLibCheck": true
  },

}

```

**Comment by messenjer** [comment]
Yes, we use it like that in our projet and doesn't have this error.

I will test it again in a new project.

**Comment by snmuhein** [comment]
I just created a minimal project to reproduce the issue:
https://github.com/snmuhein/bootstrap-vue-3-issue-392

**Comment by messenjer** [comment]
Yes, I have the same error with your project. 

Here is mine : https://github.com/messenjer/bootstrap-vue-3-issue-392 where I install the project with `npm init vue`

Do you use the vue-cli our vue-create ?

**Comment by messenjer** [comment]
with vue-create they use vuejs/tsconfig https://github.com/vuejs/tsconfig/blob/main/tsconfig.json#L38 where `"skipLibCheck": true,`

**Comment by snmuhein** [comment]
At the time when I created the project with vite, skipLibCheck was not added tsconfig. If I create a new project now skipLibCheck is part of tsconfig.

I added `"skipLibCheck": true` to my existing project, now it builds without errors. 

So I guess the issue can be closed.

**Comment by messenjer** [comment]
I remove it the import of `Reactive` type because it doesn't exit. PR here : https://github.com/cdmoro/bootstrap-vue-3/pull/393

@aceofwings it's ok for you ? I saw that your are the author of BToast.

**Comment by aceofwings** [comment]
I saw that, just now, looks good thanks for the update.
