### ISSUE TITLE
Form spin button

### ISSUE THREAD

**Issue by edwh** [cdmoro/bootstrap-vue-3#396]
Will this project support https://bootstrap-vue.org/docs/components/form-spinbutton ?

**Comment by edwh** [comment]
Excellent. Thank you.

**Comment by aceofwings** [comment]
@VividLemon if you haven’t already , I’ve been writing this component up

**Comment by VividLemon** [comment]
> @VividLemon if you haven’t already , I’ve been writing this component up

No, the functionality was a bit too complex for me to justify for a pre 1.0 custom component. 👍

**Comment by aceofwings** [comment]
#804 Completed Spin Button.
