### ISSUE TITLE
Maybe package-lock.json should not be part of repository?

### ISSUE THREAD

**Issue by Radouch** [cdmoro/bootstrap-vue-3#4]
`package-lock.json` caused a problem when I tried `npm install` on Windows. Perphaps it should not be included?

**Comment by cdmoro** [comment]
I use yarn as a package manager. Try using `yarn` command instead of `npm install`. BTW, I already delete `package-lock.json`, update the project before running any command!

**Comment by Radouch** [comment]
Now it seems be OK, thanks.

The problem was that `package-lock.json` forced installation of _fsevents_ library which should not be installed on windows machine.
