### ISSUE TITLE
Custom element error when using Vitest + Vue Testing Library

### ISSUE THREAD

**Issue by lanlegion** [cdmoro/bootstrap-vue-3#405]
The error:

**Failed to resolve component: b-collapse
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.**

This is just one component, it occurs for every bootstrap component AFAIK.

Adding it as a custom element (obviously) doesn't work.

**Comment by aceofwings** [comment]
Hi you need to provide the steps and methods that is causing this error.

**Comment by lanlegion** [comment]
I get the warning in the terminal when I run the Vitest command. It happens when I run a test with any b-component in Vitest.

The test code in bootstrapTest.test.js:
```
import { render } from '@testing-library/vue'
import { test } from 'vitest'
import TestBootstrap from '../mock/TestBootstrap.vue'

/**
 * Test Bootstrap component
 */
test('Test', async () => {
  const { getByText } = render(TestBootstrap)
})
```

The TestBootstrap.vue component:
```
<template>
  <b-card> </b-card>
</template>
```

The warning:
![image](https://user-images.githubusercontent.com/14370250/174437218-525cf51a-8668-4049-b695-d74fe615f02a.png)


It's only a warning but it seems like it causes various fatal errors/problems during testing.

**Comment by VividLemon** [comment]
This happens when either a component does not import a child component, or when you yourself do not import the child component in the test. None of these instances occur at this moment and will be only caused by contributor error.
