### ISSUE TITLE
Collapse not closing

### ISSUE THREAD

**Issue by vasim-cn** [cdmoro/bootstrap-vue-3#420]
Collapse not closing when used with bootstrap 5.1.3 and vue 3

**Comment by VividLemon** [comment]
They haven't been working on Nuxt. However, in current "builds" there doesn't seem a noticeable issue. There's been some TS issues preventing newer builds.

**Comment by VividLemon** [comment]
Since no further response has been made, I am going to close this as stale. I assume it's a non-issue with the currently updated versions.
