### ISSUE TITLE
i'm using bootstrap-vue-3  & getting  error

### ISSUE THREAD

**Issue by nageshkumawat** [cdmoro/bootstrap-vue-3#422]
Uncaught ReferenceError: BToast is not defined

please tell me how to  use bootstrap toast in vue.js

**Comment by Mowa-zee** [comment]
I think Btoast is in development.
check it out: https://cdmoro.github.io/bootstrap-vue-3/reference/parityList.html#toasts

**Comment by nageshkumawat** [comment]
Thankyou 

@Mowa-zee

**Comment by MrTanoshii** [comment]
I'm on `0.0.13` and using https://cdmoro.github.io/bootstrap-vue-3/components/Toast.html

Can you try again?

**Comment by MrTanoshii** [comment]
Great, please close the issue
