### ISSUE TITLE
Create a new branch dev for the script setup migration

### ISSUE THREAD

**Issue by messenjer** [cdmoro/bootstrap-vue-3#427]
Hello, 

@VividLemon, @mariusa , @aceofwings, 

Currently, there are many changes to transform all the components to `script setup`. I think it's a very good thing to switch to `script setup`, and it's also the way I work on all my projects in vue+typescript

But if you run the dev app `npm run dev`, there are certain things that don't work anymore and it's not easy to know if it was the case before ... and if it's linked to the migration

Could we create a `dev` branch for this migration and merge the pull-requests related to the migration on it? 

We could also remove all commits related to this migration from `main`. To be able to do a better review of the migration and to be able to compare with the pre-migration version (using a Pull Request). 

You can do this by creating the dev branch from main

```bash
git checkout -b dev
git push --set-upstream origin dev
```

Remove main

```
git branch -D main
```

Return to this commit a9f8b95f6636631a8de0 (just before the migration)

```bash
git checkout a9f8b95f6636631a8de0
```
Recreate the main branch from this commit

```bash 
git switch -c main
```

Force-push it

```bash
git push -f --set-upstream origin main
```

That would allow us to do a better review of the migration to script setup and compare 

I did the test here on my repo fork, then here is the PR of the new dev branch on the main https://github.com/messenjer/bootstrap-vue-3/pull/1/files 

What do you think?

Mathieu

**Comment by aceofwings** [comment]
I agree Mathieu,

These changes have been bringing in several disruptions. The fact that the library has not been built from errors existing since April  and also affecting documentation. We would then revert main back to the last known successful build or I assume the commit hash you provided is sufficient?

@mariusa I also think we should give window for review, just to make sure things look good. Perhaps keeping pull requests open for 24 hours? Of course this will depend on the Pull Request and what it affects.

I will do the necessary changes once we are all in agreement.

**Comment by VividLemon** [comment]
I have no objection to moving to a separate branch. However, some of the various changes to tsconfig, package.json, etc should be kept. Without some of those changes, the library will break down. For example, reverting back to pre- vue-tsc addition, will not allow the library to be built or use npm run dev. Do to the breaking issues on running build, the "prepare" script would not allow one to run npm install. I figured since the library cannot be built anyways, that there is little change. I can continue the work for script setup conversions on a different branch, then deal with the possibility of merge conflicts later. You mentioned some things not working anymore, many of the components do not contain tests so it can be hard to tell when one thing breaks. If you could provide me some examples of components that have stopped working, that would be a great place to start -- since the next list of my work is to make sure everything is working right. @aceofwings you're good to move over some of the more recent changes to a separate branch. But, if you could preserve some of the changes to the config files, that would keep the library in a stable place for anyone else starting to develop.

**Comment by mariusa** [comment]
> @mariusa I also think we should give window for review, just to make sure things look good. Perhaps keeping pull requests open for 24 hours? 

Ok, good idea!

> However, some of the various changes to tsconfig, package.json, etc should be kept. 

Right. What would be the remaining effort to complete the migration? I have the sensation that the bulk has been done already.
If so, and considering that the build was broken anyway for some time, personally I'd prefer to focus on completing and getting it working in `main`, to avoid some double work.

> I will do the necessary changes once we are all in agreement.

Whatever you prefer, @aceofwings, I agree.

**Comment by messenjer** [comment]
We can continue on main. How can we help, there are still components to convert like BButton, ... I can try to work 1h per day to convert or test components.

**Comment by VividLemon** [comment]
> We can continue on main. How can we help, there are still components to convert like BButton, ... I can try to work 1h per day to convert or test components.

As I have noted in some previous PRs. There are some limitations with Vues compiler. It does not allow extending of interfaces. So, I believe bbutton extends blink - if I remember correctly. So, for now, it can stay how it is. There are a few similar cases. The only recommended change I have done in those cases was just to improve the code.

The only remaining things to do is convert those that use render functions, and to fix out any unintentional problems with ones that have already been converted. Once those two things are finished, the library should be buildable and function properly.

**Comment by VividLemon** [comment]
> there are still components to convert like BButton

To clarify, https://vuejs.org/guide/typescript/composition-api.html#typing-component-props
means that if we were to do: 
```ts
import SomeInterface from '...'
defineProps<SomeInterface>()
```
It is not allowed
You can do (I think)
```ts
interface BLinkProps {}
interface BButtonProps extends BLinkProps {} // declared in the same file
defineProps<BButtonProps>()
```
Though, it comes with two drawbacks. 1. It means that the BLinkProps interface would be duplicated, meaning that you would need to change BLinkProps in this file also if you were making a change.
But the real issue in this example comes from trying to get the defaults from BLink
For example
```ts
import {BLinkPropDefaults} from '...'
interface A {}
interface B extends A {}
withDefaults(defineProps<B>(), { ...BLinkPropDefaults, foo: 'a' })
```
This following code errors out, claiming that the "second argument in withDefaults must be an object literal"
So currently, there are some syntax limitations with being able to pull, extend, and use props from multiple components. Hypothetically, you could again duplicate both the props interface, and it's defaults, but that would mean handling multiple files if one needed to be changed. I heard that the import of some fixes for these limitations may be coming in Vue 3.3, but this is speculation. But for now, keeping those complex components in the way that they are is of more benefit. 

For now, the only remaining work to be done is to convert the render functions (these are the only ones remaining with errors), and to fix out any issues I may have unintentionally caused. -- A known issue of mine is, as I have been saying, unintentionally making props required=true, when previously they were not explicit. I would estimate that it could probably be a week till everything is stable and buildable.

**Comment by VividLemon** [comment]
After https://github.com/cdmoro/bootstrap-vue-3/pull/428 I don't believe I can fix the remaining issues on my own. Some are caused from render functions, which I simply don't know how to fix or convert. Botast/plugin, I don't think I could confidently change, the == error, I'm not sure if setting it to === would be a competent fix, though the other issue I believe is as simple as doing ` ?? ''`. I really have no idea on how to fix the issue in utils/bvEvent or the one in BNavItemDropdown. There aren't a lot of actual errors there, I am just not confident that I would be able to fix them without introducing a separate issue. So, if someone could help me fix them, or fix them yourselves, that would be great. After that, the library could be buildable, but we would still need to be careful about any unintended, non-erroring issues that I may have caused. I don't think there is many. 

Lastly, and sadly, there are more previously unknown issues surrounding defineProps and script setup conversion, that should be eventually fixed. I submitted this issue to Vue/core https://github.com/vuejs/core/issues/6196 . I just wanted to make it known that there is another known issue with using this kind of syntax. It seems like every other day I'm finding another issue with moving to setup 😮‍💨 It doesn't do anything, beyond expressing a Vue console.warn. It should not break anything. Just can be misleading.

**Comment by mariusa** [comment]
Thank you!

**Comment by aceofwings** [comment]
Ill take a stab. Lets merge in the current fixes and go from there

**Comment by VividLemon** [comment]
> Ill take a stab. Lets merge in the current fixes and go from there

I have some other changes, I was wondering if any prop in the library was actually required. To be honest, I don't think bootstrap vue ever actually required a prop. Turning all props to not be required, causes no errors (besides like two, fixable issues). It seems like all props are treated as if they are not required to use a component. Should I pr to have all props not be required? Or does someone have any better ideas?

**Comment by mariusa** [comment]
> Turning all props to not be required, causes no errors (besides like two, fixable issues). 
> Should I pr to have all props not be required?

Great, let's do this!
