### ISSUE TITLE
BFormCheckbox does not emit the change event when label clicked

### ISSUE THREAD

**Issue by jclijmans** [cdmoro/bootstrap-vue-3#43]
When clicking on the checkbox input element, a "change" event is emitted.
Clicking on the label of the checkbox does toggle the checked value, but no "change" event is emitted.
This could lead to problems when an application relies on the change event.

Reason :
The generated label tag has no "for" attribute. And secondly, the id of the input element can be undefined which also results in no event emitted even when the for attribute of the label is correctly set.

The solution I propose, is to set the for attribute on the label and to set the default value of prop id to getID (from util).

I can create a PR for it, but I'm waiting for PR #42 to be completed because it also involves the BFormCheckbox

**Comment by cdmoro** [comment]
The PR #42 has been merged, feel free to create a PR for this issue :smiley:
