### ISSUE TITLE
missing files in 0.1.13?

### ISSUE THREAD

**Issue by amery** [cdmoro/bootstrap-vue-3#430]
I don't know if this is related to nuxt, pnpm or bootstrap-vue-3 itself. but I just tried to use `<b-container>` and... meh.
```
ERROR  Failed to resolve import "../types/position" from "../../node_modules/.pnpm/bootstrap-vue-3@0.1.13_bootstrap@5.1.3/node_modules/bootstrap-vue-3/src/components/BContainer.vue". Does the file exist? (repeated 4 times)
```

I can see `position.d.ts` there. any suggestion on how to fix this?

**Comment by amery** [comment]
it's worth mentioning cloning the repo as another package on the workspace works "fine" (leaving aside all the eslint errors)

**Comment by VividLemon** [comment]
Position.d.ts was renamed to be capitalized. Though, this happened recently and wouldn't affect an old release. I'll check to make sure the imports are correct, but I'm pretty sure it may be fixed already as I would have seen an error.

**Comment by amery** [comment]
> Edit: in some release the import was made into '@/types' so this should not be an issue.

I did have a lot of problems related to the `@` alias when using bootstrap-vue-3 directly from git... is this the kind of thing using the release or using `transpile` in nuxt.config would fix?

is a 0.1.14 overdue?

**Comment by VividLemon** [comment]
> > Edit: in some release the import was made into '@/types' so this should not be an issue.
> 
> I did have a lot of problems related to the `@` alias when using bootstrap-vue-3 directly from git... is this the kind of thing using the release or using `transpile` in nuxt.config would fix?
> 
> is a 0.1.14 overdue?

The import alias has never appeared in a release. There's four errors currently limiting building a new release.

**Comment by VividLemon** [comment]
@amery does the issue persist in the latest release?

**Comment by amery** [comment]
@VividLemon yes, 0.1.14 works fine :) thank you!

**Comment by amery** [comment]
@VividLemon the actual problem seems to be related to `..`
I made a small test case with 0.1.14 at https://gitlab.com/mnemoc/bootstrap-vue-3-nuxt
```
$ pnpm build
> @ build /xxx/src/packages/bootstrap-vue-3-nuxt
> nuxt build

Nuxt CLI v3.0.0-rc.4                                                                                                                               17:35:11
vite-plugin-stylelint enabled                                                                                                                      17:35:15
ℹ Vite client warmed up in 2480ms                                                                                                                  17:35:17

 ERROR  [vite:load-fallback] Could not load /xxx/src/packages/bootstrap-vue-3-nuxt/src/components/BButton/BButton.vue (imported by ../../../node_modules/.pnpm/bootstrap-vue-3@0.1.14_bootstrap@5.1.3/node_modules/bootstrap-vue-3/src/components/BModal.vue): ENOENT: no such file or directory, open '/xxx/src/packages/bootstrap-vue-3-nuxt/src/components/BButton/BButton.vue'


 ERROR  Could not load /xxx/src/packages/bootstrap-vue-3-nuxt/src/components/BButton/BButton.vue (imported by ../../../node_modules/.pnpm/bootstrap-vue-3@0.1.14_bootstrap@5.1.3/node_modules/bootstrap-vue-3/src/components/BModal.vue): ENOENT: no such file or directory, open '/xxx/src/packages/bootstrap-vue-3-nuxt/src/components/BButton/BButton.vue'
```

**Comment by VividLemon** [comment]
I'll review the exact behavior, and possibly try to find a solution, but any ssr is not fully supported until bootstrap makes their 5.3 (I think) ssr fixes

**Comment by amery** [comment]
@VividLemon as you can see on `package.json` I'm using a fork bootstrap 5.1.3 which is SSR friendly.
https://github.com/xvaara/bootstrap

**Comment by VividLemon** [comment]
> https://gitlab.com/mnemoc/bootstrap-vue-3-nuxt

So I had two issues when trying this here. First is that your dependency for bootstrap was called "boostrap". Which will cause a major issue. After fixing the name, it tried to load, but encountered one of our issues for using aliases that was fixed last night. After I imported 0.1.16, it loaded up fine, however, the css didn't work. So I also needed to add `css: ["bootstrap/dist/css/bootstrap.min.css"]` to nuxt.config . After I did that, everything ran and worked. 
![image](https://user-images.githubusercontent.com/31498096/178280640-bc99724c-ef70-4b8f-8ad5-ed2187674b56.png)

**Comment by messenjer** [comment]
There is an explanation here, also

https://cdmoro.github.io/bootstrap-vue-3/getting-started/#installation-nuxt-js-3

**Comment by mariusa** [comment]
Is this still an issue with the current published release?

**Comment by VividLemon** [comment]
It's fixed on the dev branch.

**Comment by mariusa** [comment]
@aceofwings @VividLemon when shall we merge dev into main?

**Comment by VividLemon** [comment]
> @aceofwings @VividLemon when shall we merge dev into main?

The intention was to test some things and make sure it works. But once I finish up a couple of things it could be released and any issues could be fixed later, if any.

**Comment by VividLemon** [comment]
> Is this still an issue with the current published release?

Actually, this was my mistake, I confused this issue with this https://github.com/cdmoro/bootstrap-vue-3/issues/487 . This issue should be fixed in the latest release, but the mentioned issue is fixed in dev branch. I'm fairly certain that this issue can be closed
