### ISSUE TITLE
How can I use only single components from  bootstrap-vue-3

### ISSUE THREAD

**Issue by amjadaliup** [cdmoro/bootstrap-vue-3#439]
I need to import only some components from bootstrap-vue-3 no need to include bootstrap-vue-3 globally. so I can reduce my code size. I tried code like this:-
`import {BRow} from 'bootstrap-vue-3';`
`export default {`
`  components: { BRow }`
`}`

but when I only importing BRow then also the build size is high (increasing around 180kb).
how can I import only one component with only that components size.
And also when I using Bdropdown, BPopover, etc and it's directives locally then some of the functionality is not working properly.
My idea is to reduce the size of the entry point.

Thanks in advance.

**Comment by aceofwings** [comment]
I will investigate this as seen in this issue. I think Its really setting up the library for tree shaking. 

#364

**Comment by VividLemon** [comment]
> I will investigate this as seen in this issue. I think Its really setting up the library for tree shaking.
> 
> #364

Perhaps this could help https://github.com/antfu/unplugin-vue-components

**Comment by edwh** [comment]
@aceofwings Thanks for looking into this.

**Comment by VividLemon** [comment]
This is unlikely to be worked on anytime soon, **but will eventually be added**. Considering the lack of activity in the thread, I am going to close it.

**Comment by mariusa** [comment]
Agreed, not a priority. Code size was already reduced a lot by removing `b-icon`.

**Comment by edwh** [comment]
I still find bootstrap-vue quite large in my build.  Is there a workaround where I can just import the components I need from the src folder, perhaps?

**Comment by mariusa** [comment]
vite visualizer shows rendered size 205kb. In my project, that's 11%.

> Is there a workaround where I can just import the components I need from the src folder, perhaps?

I don't know, but maybe keeping a local copy of some components would work.

**Comment by VividLemon** [comment]
I was thinking previously about some possible changes that could be made. Following the https://getbootstrap.com/docs/5.2/customize/optimize/ , It may be possible to have each component only import it's own css, it's own js. Most components that need Bootstrap JS already get them this way. I tried testing this though, and it didn't seem like there was much change in the projects visualizer. So, I'm curious if it would affect a user of the library. I believe it may be a factor in a future where treeshaking was fully supported, preferably even automated. As you wouldn't need to import a huge scss file in your project that you don't need. 

With that aside, I would like _eventually_ to have this process be automated. Similar to Vuetify-loader, or even, bootstrap-vue-loader. However, right now, my time is being spent developing new features and fixing bugs.

**Comment by mariusa** [comment]
> my time is being spent developing new features and fixing bugs.

Thank you for this. Optimizing 205kb to be slightly less isn't important for 1.0.

**Comment by gtempesta** [comment]
Let me know if this can help: https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/364#issuecomment-2624713157
