### ISSUE TITLE
BFormCheckbox plain property not compatible with bootstrap-vue

### ISSUE THREAD

**Issue by jclijmans** [cdmoro/bootstrap-vue-3#46]
In bootstrap-vue-2, the plain property seems to behave exact the opposite of the behavior of bootstrap-vue.

In bootstrap-vue from the documentation :
property plain, type Boolean, Default false, Render the form control in plain mode, rather than custom styled mode

In bootstrap-vue-3, the plain property has default value true and it's behavior is exactly the opposite of the behavior in bootstrap-vue.
If I set the property plain to true, the checkbox is rendered in custom styling.

This seams to me to be very confusing. If I set the plain property to true, I expect it to rendered plain (As the browser renders it)
Also it's not helping people migrating from bootstrap-vue.

Is this intentionally, or is this a bug?

**Comment by jclijmans** [comment]
@cdmoro : Do you agree that this is a bug and needs to be fixed?

If you agree, I'll have a look at reversing the plain property behavior

**Comment by cdmoro** [comment]
Yes, this is a bug, definitely. It would be nice if you could fix it, thanks!
