### ISSUE TITLE
Sorteable, filter, and sort doens't work b-table?? 

### ISSUE THREAD

**Issue by carlosbelchior** [cdmoro/bootstrap-vue-3#462]
I'm using Vue3 and i test b-table, show data it's ok, but, i try use sorteable column and don't work.

`
<b-table
        striped
        hover
        responsive="sm"
        :items="clientes"
        :fields="fields"
        :sort-by.sync="sortBy"
        :sort-desc.sync="sortDesc"
        sort-icon-left>
        <template v-slot:cell(acao)="{ item }">
            <router-link class="btn btn-primary btn-sm" :to="{ name: 'clientes-formulario', params: { id: item.id }}">Editar</router-link>
            <button class="btn btn-danger btn-sm mx-2" @click="excluirCliente(item.id)">Excluir</button>
        </template>
`

`
return {
                sortBy: 'id',
                sortDesc: false,
                fields: [
                    { key: 'id', label: 'ID', sortable: true },
                    { key: 'nome', label: 'Nome', sortable: true },
                    { key: 'cpf', label: 'CPF', sortable: true },
                    { key: 'email', label: 'E-mail', sortable: true },
                    { key: 'acao',label: 'Ação', sortable: false }
                ],
                clientes,
                excluirCliente,
            };
`

**Comment by mariusa** [comment]
This isn't implemented: https://cdmoro.github.io/bootstrap-vue-3/components/Table.html
You might want to read the docs in advance.
