### ISSUE TITLE
TypeError while running jest

### ISSUE THREAD

**Issue by eunsukimme** [cdmoro/bootstrap-vue-3#465]
When I run jest on my workspace, an error emitted like:

```
TypeError: Cannot read properties of undefined (reading '__vccOpts')
```
<img width="829" alt="Screen Shot 2022-07-11 at 1 04 40 PM" src="https://user-images.githubusercontent.com/31213226/178186533-8b341589-648e-4471-be1e-ac0d1e658c0d.png">

How can I fix it? Thanks!

**Comment by mariusa** [comment]
` npm run test` works fine now
```
bootstrap-vue-3:test: Test Files  16 failed (16)
bootstrap-vue-3:test:      Tests  298 failed | 71 passed | 1 skipped (370)
bootstrap-vue-3:test:   Start at  14:42:48
bootstrap-vue-3:test:   Duration  8.54s (setup 8ms, collect 8.27s, tests 2.22s)
```
