### ISSUE TITLE
Publish latest versions of the package on npm

### ISSUE THREAD

**Issue by danielelkington** [cdmoro/bootstrap-vue-3#467]
I can see that tags have been created for versions 0.1.15 and 0.1.16, however the [latest version on npm is 0.1.14](https://www.npmjs.com/package/bootstrap-vue-3). Could the latest version please be published to npm?

**Comment by MrTanoshii** [comment]
Agreed, or at least revert to a previous version on npm as `0.1.14` broke a few things

**Comment by VividLemon** [comment]
> Agreed, or at least revert to a previous version on npm as `0.1.14` broke a few things

What is broken?

**Comment by mariusa** [comment]
The next PR triggering release bot should also publish to npm.

**Comment by mariusa** [comment]
As you wish :)

**Comment by apawelec** [comment]
Looks like still the latest version on npm is 0.1.14
