### ISSUE TITLE
Compiler error when trying to run the docs site

### ISSUE THREAD

**Issue by jclijmans** [cdmoro/bootstrap-vue-3#47]
Hello,

After contributing to the BFormCheckbox component, I thought it might be good to have some documentation about it.
So I started to look into the doc site

I tried to compile the site locally by running "yarn run docs:dev", but this gives a compilation error

Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[1].resource.test: resource => {
        currentResource = resource
        return true
      })

It seems this is an issue with vue-loader
Updating this does not work because there are inconsistent version requirement for vue-loader
vue-cli-service needs vue-loader "^15.9.2"
vuepress needs vue-loader "^16.5.0"

It would be nice to have a contribution guide on how to setup your local dev environment to be able to contribute.

Thanks for your effort

**Comment by mariusa** [comment]
I've fixed this in https://github.com/cdmoro/bootstrap-vue-3/pull/48
with the new vite build
