### ISSUE TITLE
Btabs abd Btab are not working.

### ISSUE THREAD

**Issue by sanjayosx** [cdmoro/bootstrap-vue-3#489]
I have been using BTabs and BTab previously. Not it has stopped working. 

I downgraded to 0.1.10 version but still the same.

**Comment by MrTanoshii** [comment]
Do you have a minimal reproduction project?

I've also been using BTabs without any issue until `0.1.14`
Are you sure your `bootstrap-vue-3` in  `package-lock.json` is below `0.1.14`?

![image](https://user-images.githubusercontent.com/47116127/179477057-ddfdcdf7-f696-4a78-be2a-0b08e6a260e2.png)

**Comment by sanjayosx** [comment]
Here is the screenshot:
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/92869499/179477569-9168b7fd-a115-45cf-90ec-345a292a5c8f.png">

**Comment by MrTanoshii** [comment]
That's running `0.1.14` as you can see on line 3906, revert back to `0.1.13` or use the latest from GitHub

**Comment by MrTanoshii** [comment]
Please close the issue

**Comment by sanjayosx** [comment]
Downgraded to 0.1.13 and issue resolved.
