### ISSUE TITLE
<script src=...

### ISSUE THREAD

**Issue by skipware-oz** [cdmoro/bootstrap-vue-3#494]
As with boostrap-vue we can load inline with:
`<script src="../uibuilder/vendor/bootstrap-vue/dist/bootstrap-vue.min.js">/* remove 'min.' to use dev version */</script>`

Is this possible wit bootstrap-vue-3 or is their plans to povide for this?
I ask because in my implimentation I want develop without a build step.

**Comment by VividLemon** [comment]
I've never heard of it be used like that. If you could provide some documentation on how this works, that would be nice. But dist/bootstrap-vue-3 provides bootstrap-vue-3.es.js & bootstrap-vue-3.umd.js that you _might_ be able to use.

**Comment by VividLemon** [comment]
Since there has been no further input on this specific use case, I am going to close the issue. Reopen if you have any additional questions on this issue.
