### ISSUE TITLE
src/BootstrapVue.ts: some components have no exported member 'default'

### ISSUE THREAD

**Issue by DavidGalicia** [cdmoro/bootstrap-vue-3#505]
When I open `src/BootstrapVue.ts` in WebStorm, I see this error for BTabs:

![bootstrap-vue-error2](https://user-images.githubusercontent.com/193476/181382440-7e400b01-d838-4507-a57f-9e83288b759a.PNG)

Is this an error I can opt in to fix? Would this error be taken care of in #487 ?

**Comment by VividLemon** [comment]
It should. That format isn't used in future commits.

**Comment by DavidGalicia** [comment]
You're right because `<script setup>` is implied to be the default export.

I found the error can be worked around when this section in `BTabs.vue`:

```typescript
<script lang="ts">
import {BTabsParentData} from '../../types/components'
export const injectionKey: InjectionKey<BTabsParentData> = Symbol()
</script>
```

is moved to the top and updated like so:

```typescript
<script lang="ts">
import {computed, defineComponent, InjectionKey, onMounted, provide, ref, useSlots, watch} from 'vue'
import {BTabsParentData} from '../../types/components'
export const injectionKey: InjectionKey<BTabsParentData> = Symbol()

export default defineComponent({
  name: 'BTabs',
})
</script>

<script setup lang="ts">
// import type {BTabsProps, BTabsEmits} from '../types/components'

import getID from '../../utils/getID'
import type {Alignment} from '../../types'
import {BvEvent} from '../../utils/bvEvent'
import {mathMax} from '../../utils/math'
import {isFunction} from '../../utils/inspect'
// ...
```

That way the IDE reports no error.

Another way to correct the error is by having descendant components use a string instead of a symbol to refer to an injection value.

Can you tell more about the format? Does it mean how a component is imported? Thanks!

**Comment by VividLemon** [comment]
> Can you tell more about the format? Does it mean how a component is imported? Thanks!

Not sure what you mean.

> ```ts
> export default defineComponent({
>   name: 'BTabs',
> })
> ```

This would cause a vue-tsc compiler issue. Specifically a runtime issue.

**Comment by DavidGalicia** [comment]
> It should. That format isn't used in future commits.

I was wondering what format means above.

In my dev environment, the section

```
export default defineComponent({
  name: 'BTabs',
})
```

doesn't cause an error when the sfc is specifically built, imported and used in a test page. But code above is causing an issue like you said so I wouldn't recommend writing more modules like that.

I noticed `npm run build` will build the unmodified code and not throw the error mentioned by my ide. What ide and typescript version do you use for development? That might explain why I don't see the same errors as you do.

**Comment by VividLemon** [comment]
> > It should. That format isn't used in future commits.
> 
> I was wondering what format means above.
> 
> In my dev environment, the section
> 
> ```ts
> export default defineComponent({
>   name: 'BTabs',
> })
> ```
> 
> doesn't cause an error when the sfc is specifically built, imported and used in a test page. But code above is causing an issue like you said so I wouldn't recommend writing more modules like that.
> 
> I noticed `npm run build` will build the unmodified code and not throw the error mentioned by my ide. What ide and typescript version do you use for development? That might explain why I don't see the same errors as you do.

It won't break even __you__ write code like that, but it will break for libraries generating types files. `export {default as *}` isnt used in the main file. The main file in the next release is different. I've included a change addressing this, but lmk of when the next release is out, that it continues to behave the same. I use vscode and latest ts.

**Comment by DavidGalicia** [comment]
I opened `src/BootstrapVue.ts` in VS Code on linux and I don't see an error from the IDE. The editor is using Typescript 4.7.3.

I need to see if Webstorm has options set that is causing the error.
