### ISSUE TITLE
[docs] Modal is missing on the components page

### ISSUE THREAD

**Issue by bperel** [cdmoro/bootstrap-vue-3#507]
On the [component](https://cdmoro.github.io/bootstrap-vue-3/components/) page, Modal is not listed even though this component is available.
It could be useful to have a reference point about the supported props, since for instance `placement` is not supported.

**Comment by VividLemon** [comment]
https://github.com/cdmoro/bootstrap-vue-3/issues/491

**Comment by bperel** [comment]
Hmm, I'm not sure how the related issue answers the current issue: it shows a usage example but the issue still remains that there is no documentation for this component. Or did I miss something?

**Comment by VividLemon** [comment]
The point is that it is known, and [Atokulus](https://github.com/Atokulus) documented a good usage example for those unsure of how to start.

**Comment by VividLemon** [comment]
I am going to close the issue since there has been no additional reply or question. It is known that the documentation is not fully completed. At the time, the best option is to review other comments on how to start, and the props/emits/slots in the .vue file
