### ISSUE TITLE
implement b-table select rows feature

### ISSUE THREAD

**Issue by ahmedrazaa** [cdmoro/bootstrap-vue-3#535]
Hi there, any update regarding the package update. I'm looking for the select row feature which I was using with vue 2 previoulsy? here was that code but its no more working with vue3.
 <b-table
            :items="ColumnsList"
            :fields="fields"
            :select-mode="selectMode"
            responsive="sm"
            ref="selectableTable"
            selectable
            @row-selected="onSelectedRow"
          >
            <template v-slot:cell(selected)="data">
              <b-form-group>
                <input
                  type="checkbox"
                  @change="selectRow(data)"
                  v-model="data.rowSelected"
                />
              </b-form-group>
            </template>

**Comment by VividLemon** [comment]
That feature isn't available yet.

**Comment by ahmedrazaa** [comment]
@VividLemon is there any idea when this feature will be available

**Comment by VividLemon** [comment]
No

**Comment by devhus** [comment]
I will try my best to bring that feature to the library through #609 PR ✌🏼

**Comment by VividLemon** [comment]
@ahmedrazaa Could you review a latest update and determine if this issue can be considered closed?

**Comment by ahmedrazaa** [comment]
@VividLemon will review this feature today, and then inform you

**Comment by VividLemon** [comment]
Assumed completed
