### ISSUE TITLE
Developing Docs

### ISSUE THREAD

**Issue by aceofwings** [cdmoro/bootstrap-vue-3#538]
Looking at running Docs in development mode.

Getting some sort of run time error? I'll narrow it down later.

`TypeError: Cannot read properties of undefined (reading 'value') config.ts 10 `

@VividLemon How have you been a to run Docs Dev and if so what steps did you take?

**Comment by VividLemon** [comment]
> Looking at running Docs in development mode.
> 
> Getting some sort of run time error? I'll narrow it down later.
> 
> `TypeError: Cannot read properties of undefined (reading 'value') config.ts 10 `
> 
> @VividLemon How have you been a to run Docs Dev and if so what steps did you take?

When I was making the pnpm transition, I attempted to open the docs, and the same issue occurred. I was confused so I reverted back before those commits and was facing the same issue. I attempted to work out a fix, but could not figure it out. Oddly, building and publishing the docs works just fine.

**Comment by aceofwings** [comment]
Yeah I tried to remove everything except for the bare basics. No luck. Might be a path resolving issue. Attempted to run the command through several of the project directories without success.

**Comment by VividLemon** [comment]
You could try to look on their github if there's any issue like it, or post an issue

**Comment by aceofwings** [comment]
Didn’t see anything but I’m go to rebuild the directory structure like you said and go from there
