### ISSUE TITLE
BAvatar shows `false false` before avatar ({{ badgeLeft }}   {{ badgeLeftBoolean }})

### ISSUE THREAD

**Issue by mariusa** [cdmoro/bootstrap-vue-3#550]
https://github.com/cdmoro/bootstrap-vue-3/blob/104b083d1e868fc0b40d9ac552daba601518b6b9/packages/bootstrap-vue-3/src/components/BAvatar/BAvatar.vue#L2

Also replicable in playground. Not sure how these were working in 0.1.x
```
{{ badgeLeft }}
{{ badgeLeftBoolean }}
```

**Comment by mariusa** [comment]
They weren't present before: https://github.com/cdmoro/bootstrap-vue-3/blob/b96867ffef735b1ea44c4475cf2d56223ac96fd1/src/components/BAvatar/BAvatar.vue

Were these added for debugging and forgotten?

**Comment by VividLemon** [comment]
I woke up and the first thing I thought of was... "Did I leave that debug code in? 🤔 "
