### ISSUE TITLE
Possible to use `:value` and `@input` instead of `v-model` on ´BFormInput`?

### ISSUE THREAD

**Issue by simensol** [cdmoro/bootstrap-vue-3#558]
I have a `BFormInput` form field which need more complex behavior than `v-model` supports. Thus, I have to use `:value` and `@input` instead:

```vue
<BFormInput
    :value="getClaimAmount()"
    @input="
        (event) => {
            setClaimAmount(
                event.target.value,
                claim_index
            )
        }
    "
/>
```

However, I cannot get it to work. It works if I use regular HTML:

```vue
<input
    class="form-control"
    :value="getClaimAmount()"
    @input="
        (event) => {
            setClaimAmount(
                event.target.value,
                claim_index
            )
        }
    "
/>
```

It seems the getter works but not the setter. Is this by design, or is it a bug?

**Comment by messenjer** [comment]
Hello,

With Vue3, you need to set the value with `:modelValue` like that 

```vue
<BFormInput
    :modelValue="getClaimAmount()"
    @input="
        (event) => {
            setClaimAmount(
                event.target.value,
                claim_index
            )
        }
    "
/>
```

**Comment by VividLemon** [comment]
Since there has been no additional reply, I am going to close the issue. I believe with both of our notes, you should be able to get your code working properly. Reopen the issue if you have any further questions on this.
