### ISSUE TITLE
Docs dark mode component properties text does not have dark-text variant

### ISSUE THREAD

**Issue by VividLemon** [cdmoro/bootstrap-vue-3#562]
**Describe the bug**

**To Reproduce**
1. https://cdmoro.github.io/bootstrap-vue-3/components/Alert.html
2. Be in dark
3. Scroll to properties
4. Too dark contrast text

**Expected behavior**
Text should have a dark variant, that turns white, or a different high contrast color

**Screenshots**
![image](https://user-images.githubusercontent.com/31498096/185229016-cb4598fc-ec21-4efe-83e1-44b72fb371d4.png)

**Comment by aceofwings** [comment]
I have noticed this too. I think vue press changed their styling in the last few releases. Will have to update css to reflect their dark mode features.
