### ISSUE TITLE
b-img-lazy component missing

### ISSUE THREAD

**Issue by Fil923** [cdmoro/bootstrap-vue-3#564]
Hi, it seems that the component "b-img-lazy" is missing in the list of components, i can only import "b-img"

**Comment by VividLemon** [comment]
As I noted, this is not planned on being added until many other features are added or fixed. I'm sure it will come in a future release, but since it's not anticipated in the near future, I'm going to close the issue.

**Comment by VividLemon** [comment]
Implemented via the `lazy` prop in b-img. Eventually, it will be updated to include placeholder elements as courtesy. (Though, it currently emits a load event which one could theoretically use to watch for)
