### ISSUE TITLE
<b-navbar-toggle> crashes the app

### ISSUE THREAD

**Issue by ihorbond** [cdmoro/bootstrap-vue-3#565]
**Describe the bug**
When using 
```
<b-navbar>
    <b-navbar-toggle></b-navbar-toggle>
</b-navbar>
```
crashes with error
Uncaught (in promise) SyntaxError: The requested module '/node_modules/bootstrap/js/dist/popover.js?v=c0f786ef' does not provide an export named 'default' (at BPopover.ts:2:8)

**To Reproduce**
Run a Nuxt3 project with Typescript. Try to use  <b-navbar-toggle></b-navbar-toggle> in a component

**Expected behavior**
App doesn't crash

**Screenshots**
![image](https://user-images.githubusercontent.com/15573624/185419602-7e29e473-d11e-4172-8eff-6a0649513e60.png)

**Environment (please complete the following information):**
 - OS: Win 10, node v16.15
 - Version 
```
    "@popperjs/core": "^2.11.6",
     "bootstrap": "^5.2.0",
    "bootstrap-vue-3": "^0.2.8",
```

**Comment by VividLemon** [comment]
The nav components are not released, they are in 0.2.9. However, I think I've narrowed the issue and 0.2.9 will include a fix.
