### ISSUE TITLE
navbar: default padding

### ISSUE THREAD

**Issue by DavidGalicia** [cdmoro/bootstrap-vue-3#566]
The original navbar in the bootstrap-vue comes with padding at the sides so the navbar resembles the examples shown [here](https://getbootstrap.com/docs/5.2/components/navbar/) at getboostrap.com. In most of the examples a nested `div` with a `container-fluid` css class is used for the padding.

If the template markup for `BNavbar.vue` is updated from this:

```
<template>
  <component :is="tag" class="navbar" :class="classes" :role="computedRole">
    <slot />
  </component>
</template>
```

to this:

```
<template>
  <component :is="tag" class="navbar" :class="classes" :role="computedRole">
    <div class="container-fluid">
      <slot />
    </div>
  </component>
</template>
```

then you can see these changes:

Before:
![before](https://user-images.githubusercontent.com/193476/185444892-48b0fd9a-b31c-482f-9481-931521767335.PNG)

After:
![after](https://user-images.githubusercontent.com/193476/185444907-338edb72-bca6-4d70-848c-5e3ca051d334.PNG)

I noticed in [one](https://getbootstrap.com/docs/5.2/components/navbar/#image) of the examples the nested `div` has a `container` class instead.

Would you be interested in giving the navbar padding by default, which includes the sides, and allowing the user to override the nested div's css class using a vue prop?

**Comment by VividLemon** [comment]
![image](https://user-images.githubusercontent.com/31498096/185457938-744263a2-685e-4ace-9a97-d0af2ce8cb0f.png)

![image](https://user-images.githubusercontent.com/31498096/185458186-97ac0bff-a1d2-437c-bb8a-9bff43c805b6.png)

![image](https://user-images.githubusercontent.com/31498096/185458017-f1ea8f07-dae6-404b-bcd6-3fe6e87d62e7.png)

**Comment by DavidGalicia** [comment]
Awesome, thanks!
