### ISSUE TITLE
BTable info

### ISSUE THREAD

**Issue by drakaena** [cdmoro/bootstrap-vue-3#573]
Hi, I'm trying to use the BTable in my project but some functions I used before no longer work.
Like @row-clicked, @row-selected, @sort-changed, filter, busy and all the props to set classes to various thead / tbody / tfoot.

Looking at the documentation I only see indications for the BTableSimple.
Are these features missing? Do you have any idea when these changes will be released for the BTable?

**Comment by neo7337** [comment]
@drakaena Many events have not been implemented yet, have a look at the issue #138 for more details.

**Comment by VividLemon** [comment]
There is no timeline atm. Perhaps once I'm done with finishing up the current tests, I will make this a priority. It seems to be something a fair few request.

**Comment by devhus** [comment]
@drakaena most of these feature was added lately https://github.com/cdmoro/bootstrap-vue-3/pull/624, https://github.com/cdmoro/bootstrap-vue-3/pull/616, https://github.com/cdmoro/bootstrap-vue-3/pull/609, and https://github.com/cdmoro/bootstrap-vue-3/pull/594 
enjoy it.

**Comment by VividLemon** [comment]
I assume most additions are implemented, though the documentation on how to use them is not complete. I am going to close the issue
