### ISSUE TITLE
Please add the sidebar

### ISSUE THREAD

**Issue by csteele86** [cdmoro/bootstrap-vue-3#576]
**Is your feature request related to a problem? Please describe.**
Yes, we cannot use the sidebar component that is outlined in the bootstrap documentation: https://bootstrap-vue.org/docs/components/sidebar

**Describe the solution you would like**
The sidebar added

**Describe alternatives you have considered**
None at this time since I'm trying to do a hackathon!

**Additional context**

**Comment by VividLemon** [comment]
Pretty sure it's called offcanvas in Bootstrap

**Comment by VividLemon** [comment]
I'm going to close this as completed since there has been no additional reply, this should be added, just not well documented.
