### ISSUE TITLE
Multiple checkboxes: selection should keep order (?)

### ISSUE THREAD

**Issue by mariusa** [cdmoro/bootstrap-vue-3#582]
**Is your feature request related to a problem? Please describe.**
Example: https://cdmoro.github.io/bootstrap-vue-3/components/FormCheckbox.html#changing-the-option-field-names

If user clicks A, D, B, then `Selected` is `[ "A", { "d": 1 }, "B" ]`

**Describe the solution you would like**
No matter what order user clicks, `Selected` should preserve original options order, eg `[ "A", "B", { "d": 1 } ]`

**Describe alternatives you have considered**
I'm not sure if this should be handled by bootstrap-vue-3. It seems it's the default browser behavior.
What do you think?

**Comment by VividLemon** [comment]
It sounds look it could be useful, but practically speaking, if you needed specific items you would be better off using an array method like .find , with the contents of the array and the order they're in, having not much of a real effect on the outcome. 

I suppose a way to implement this would be to store an additional array. Basically, if the value has not been added yet, it will push to the end of a second storage array. If it has, do nothing. Then sort the real value by that array -- the hardest part tbh. 

Ultimately though, I'm thinking a better idea may be to add a "sort" prop. The idea being that "undefined" does no sorting, "true" sorts alphabetically, and false does reverse alphabet... don't know how non strings get sorted, but it's just an idea. Then, besides boolean | undefined, allow for a custom sort function callback. So boolean | undefined | Function . Technically though, one could do the same logic themselves with the modelValue and a simple computed function. Just convenience ig.

So, I'm not sure if it's the best approach. I suppose it could be done, just some stuff to work out. But, I'm not sure if overriding default behaviors for a relatively small impact is a good use of time.

**Comment by mariusa** [comment]
Thanks!

> But, I'm not sure if overriding default behaviors for a relatively small impact is a good use of time.

Agreed.

> Ultimately though, I'm thinking a better idea may be to add a "sort" prop. The

That wouldn't be useful. The need is to keep the order of the given options, which isn't necessarily alpha. Example: week days: Mon, Tue, Wed.... Or Age groups: 1-7, 8-10, 11-15 etc.

User selects Mon, Fri, Sat, then Tue. In the list of saved info, they see `Mon, Fri, Sat, Tue` instead of `Mon, Tue, Fri, Sat`

This would also apply to multiselect, not just checkbox group.

For a larger vision to consider, the given options might vary, eg https://vue-multiselect.js.org/ with ajax search. So here the user choices need to be kept in the order they were made. Only if the list of options is static, the order of selected items should be tweaked to match order of options.

Should I close this, or do you see this useful to be handled by the library?

**Comment by VividLemon** [comment]
If you think this is a meaningful addition, I can begin work on developing it. I've been building tests, and fixing things when I come across them while testing. So, I suppose it would be nice to work on something else. Just explain from start to finish how exactly you think it should work, and I will work on it. (Along with other components that this would work on)

**Comment by mariusa** [comment]
Thank you! I think it's a valid use case.

Components: `b-form-checkbox-group`, `b-form-select`

Testing
https://cdmoro.github.io/bootstrap-vue-3/components/FormSelect.html#value-in-multiple-mode
I see that `b-form-select` multiple already works like this. Not sure if intended, or that's the default HTML/dom behavior for select, would be good to find out. Test: select options in random order, `Selected: [ "a", "b", "e", "f" ]`. I've tested with week day values too, it keeps the order of the initial options, not alphabetical, which is expected behavior.

Test for `b-form-checkbox-group`:
```
<b-form-checkbox-group
                    v-model="multiTest"
                    :options="['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']"
                ></b-form-checkbox-group>
```

User selects in this order: Mon, Fri, Sat, then Tue. `multiTest` has `Mon, Fri, Sat, Tue` instead of `Mon, Tue, Fri, Sat`

Proposal: the component `@change` should re-order items in the order of options, before emiting the changed event.

**Comment by VividLemon** [comment]
I thought I had responded to this earlier. My point that I was making was that I was previously confused and wrong about what I thought you wanted. I understand the reasoning behind adding this, and think it's a good addition. 

I was working on this yesterday, but was unable to finish a solution. I may need help with a solution regarding the sorting. I had a sort function that sorted correctly by `string`s, but was unable to get it to sort based on anything other than a string, at which point, adding an object would break everything. So, it will take some more work.

**Comment by mariusa** [comment]
How about this?

```js
let options=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
let selection=['Thursday', 'Monday','Sunday', 'Friday']
let selectionSorted = options.filter(it=> selection.includes(it))
(4) ['Monday', 'Thursday', 'Friday', 'Sunday']
```

Avoid any sorting, just start from full options list.

**Comment by VividLemon** [comment]
Can you test around and see if this works better to include objects? 
```ts
let selectionSorted = options.filter(it=> selection.map(el => JSON.stringify(el)).includes(JSON.stringify(it)))
```
I adjusted it, and it works with objects, I'll make the changes if you could check around and see if it works correctly on all data types. 

That's a clever way of fixing my issue...

**Comment by VividLemon** [comment]
While developing this, and to make the component fully TypeScript friendly, I may remove the prop options `disabledField, textField, valueField`. In reality, both of these could coexist, but I think it may be better to remove that ability. If the values were in an object that one does not have control of, the best option for them would be to make a computed array.map that converts it into the necessary object. Do you think this is a better approach to squash out bugs and fully finish this note:  `// Objects are not supported yet`. Or, do you think it be better if I find a workaround. 

I prefer TypeScript. Though, making this change would be a breaking change. Not that in alpha it's not unexpected.

**Comment by mariusa** [comment]
Considering that options are only strings or simple objects/ (text/value), `JSON.stringify` should be good enough for comparison.

>  Do you think this is a better approach to squash out bugs and fully finish this note

Yes, since you're on this. Better to test only once.

> making this change would be a breaking change. Not that in alpha it's not unexpected.

Right. No problem. I do see value though in `textField, valueField` (not in `disabled-field`)

Use case: Similar to https://vue-multiselect.js.org/ , at some point we might support loading dynamic options via AJAX, eg user types to search. Those options come from a server, which the developer might not control. That's why it would be simpler to specify `textField, valueField` and simply point to server results, rather than changing the results first.

**Comment by VividLemon** [comment]
The way I see it, it's an either or. It's not possible to have this component (options) be both strongly typed, and be dynamic enough to allow prop.textField, prop.htmlField, etc. Dynamic abilities inherently does not allow strongly typed.  

I could code around the possibility of items being dynamic, however, if there was an error in ones code, this would be an exclusively runtime issue.

Doing something like this could _maybe_ be possible in a function, however, it is not possible when Vue is compiled and would not work in templates
![image](https://user-images.githubusercontent.com/31498096/186946036-62bdd547-45ca-4095-87b9-b3155b22b7ec.png)

**Comment by mariusa** [comment]
Please, do as you see fit. I'm not familiar enough with TypeScript.

**Comment by VividLemon** [comment]
> Those options come from a server, which the developer might not control

The user would be able to do a fetch, then map out the options to the correct format. eg 
```ts
const fetchedItems = [{textField: 'abc', valueField: 'def'}] // pretend we're awaiting a fetch call
const checkboxgroupoptions = computed(() => fetchedItems.map(el => {value: el.valueField, text: el.textField}))
```
But I agree, I don't think it would be possible to include if we `at some point we might support loading dynamic options via AJAX`. That again, would inherently be exclusive runtime code.

**Comment by VividLemon** [comment]
https://github.com/cdmoro/bootstrap-vue-3/pull/589/commits/c9b4b756c969b93747081213fd1675e5aec6342b

**Comment by mariusa** [comment]
I tested this with the latest release, works great, thank you!
