### ISSUE TITLE
text alignment classes not working (class="text-right")

### ISSUE THREAD

**Issue by memen45** [cdmoro/bootstrap-vue-3#587]
[Example](https://bootstrap-vue.org/docs/components/layout#setting-one-column-width) where aligning for the first container works as expected in both bootstrap-vue and bootstrap-vue-3, but for the second container, bootstrap-vue-3 is not aligning the text to the right at all. 
```
<b-container class="bv-example-row">
  <b-row class="text-center">
    <b-col>1 of 3</b-col>
    <b-col cols="8">2 of 3 (wider)</b-col>
    <b-col>3 of 3</b-col>
  </b-row>

  <b-row class="text-center">
    <b-col>1 of 3</b-col>
    <b-col cols="5">2 of 3 (wider)</b-col>
    <b-col class="text-right">3 of 3</b-col>
  </b-row>
</b-container>
```

Is there a way to achieve right alignment?

**Comment by makroxyz** [comment]
In bootstrap 5 is text-end not text-right.

Il ven 26 ago 2022, 15:36 memen45 ***@***.***> ha scritto:

**Comment by memen45** [comment]
Ah thanks a lot for your quick reply!
