### ISSUE TITLE
BToast don't work

### ISSUE THREAD

**Issue by no1621name** [cdmoro/bootstrap-vue-3#606]
Hello,  I'm using nuxt 3. If I try to make toast following docs and another issues, I'll get that error:
```
ReferenceError: document is not defined
```
Code:

_index.vue_
```
<template>
  <div>
    <ClientOnly>
      <BContainer
        :toast="{root: true}"
        fluid="sm"
        position="position-fixed"
      >
        <BButton @click="show1">
          toast
        </BButton>
      </BContainer>
    </ClientOnly>
  </div>
</template>

<script lang="ts" setup>
import { useToast } from 'bootstrap-vue-3';
const toast = useToast();
const show1 = () => {
  toast!.show({ title: 'example title' });
};
</script>
```
_bootstraptoast.client.ts_
```
import { BToastPlugin } from 'bootstrap-vue-3';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(BToastPlugin);
});
```

**Comment by no1621name** [comment]
I'm sorry. "Closed" is my mistake

**Comment by VividLemon** [comment]
The library isn't fully ssr friendly. I heard that Bootstrap is planning on making changes in 5.3 that allows them to be ssr friendly, and that's what we're waiting on. I believe there's a fork library of bootstrap that you may be able to use instead

**Comment by no1621name** [comment]
Ok, thanks for answer, I'll try to find it.

**Comment by VividLemon** [comment]
Closing as this is well known, but not viable until a future release of Bootstrap
