### ISSUE TITLE
select not returning undefined or null

### ISSUE THREAD

**Issue by xvaara** [cdmoro/bootstrap-vue-3#607]
Why are we converting undefined and null to empty string?

Again breaking changes that I (or my users) only notice in production. Null and undefined are valid values!
I really don't want to add test to my forms that null's aren't suddenly converted to strings...

https://github.com/cdmoro/bootstrap-vue-3/blob/6e7729739af0eac0e0bca0b7bf86106ac805193d/packages/bootstrap-vue-3/src/components/BFormSelect/BFormSelectOption.vue#L2

**Comment by VividLemon** [comment]
When doing `<option :value="null" :disabled="true">` Vue will only render `<option disabled="">` Which breaks the component when using null or undefined values. https://github.com/cdmoro/bootstrap-vue-3/issues/124

https://vuejs.org/guide/essentials/template-syntax.html#attribute-bindings
> The v-bind directive instructs Vue to keep the element's id attribute in sync with the component's dynamicId property. If the bound value is null or undefined, then the attribute will be removed from the rendered element.

Which previously would mean any null value would not be capable of being selected. 

Perhaps a better option should be to cast null and undefined as strings, and render it as `value="undefined"` or `value="null"`

**Comment by xvaara** [comment]
https://stackblitz.com/edit/vitejs-vite-ycvvwn?file=src/App.vue

seems that native works and b-form-select doesn't. Vue binds the value ref (even null) to the dom object. That is only problem if you are rendering it to html (in ssr, but after that you hydrate it to a working vue version).

btw. null was working in b-form-select in previous versions... don't know what the problem in #124 was.

undefined = value missing
null = unset value

I already removed all the b-form-select:s where the value could be null from my code, so it's same to me. It's just really weird to return a value that's different from what the user specified.

We're not building markdown, we're building dom. I might be wrong...

**Comment by VividLemon** [comment]
It's all html in the end. The same mysterious reason why disabled="false" will still be disabled. html doesn't know what any of this stuff is, it's all just strings. 

I'll re-evaluate the component, probably tomorrow, as Bootstrap-vue also follows the behavior you described. It may be possible that Vue had made a change between now and the almost year ago issue we had. Or not and it is and always has been a Bootstrap-vue-3 problem.

**Comment by xvaara** [comment]
it's not html, it's dom manipulations. Object renders in html as: value="[object Object]"

As you can see in my example, bootstra-vue-3 doesn't even select the right option if the v-model ref is null, it only seems to work on undefined.

disabled="false" is html, :disabled="false" is vue and binds to dom and works.

**Comment by VividLemon** [comment]
@xvaara with the latest changes, do you find your example you posted to be acceptable now? I recall finding undefined behavior out of line with how native selects work, but I think it still outputs undefined. Do you think the behavior is acceptable? Or is there still things I should fix regarding this component?

**Comment by xvaara** [comment]
I upgraded the dependencies in the example and it seems fine. I also think undefined is fine the way it is currently.
