### ISSUE TITLE
Table not sorting

### ISSUE THREAD

**Issue by mlevet** [cdmoro/bootstrap-vue-3#612]
I'm struggling to make my b-table sortable
Not sure what i'm doing wrong

I use : "vue": "^3.2.13"

"bootstrap-vue-3": "^0.1.6"

Also, does it support filter and pagination ?

This is my vue for now

```
<template>
  <div class="overview">
    <b-table
        sort-by="status" sortDesc
        :items="items"
        :fields="formFields.licences"
    >
    </b-table>
  </div>
</template>

<script>

export default {
  name: "licences.vue",
  data(){
    return {
      formFields: {
        licences: [
          {key: "name", sortable: true,  label: "Name"},
          {key: "status", sortable: true, label: "Status"},
        ],
      },
      items: [
        { name: "Jack", status: "Used" },
        {name: "Frank", status: "Unused"},
        {name: "Larry", status: "Used" }
      ]
      }
  }
}
</script>
```

**Comment by VividLemon** [comment]
The sort functionality was recently added in >[0.2.13](https://github.com/cdmoro/bootstrap-vue-3/releases/tag/v0.2.13). You should update your version

`name: "licences.vue",`
Your component names need to be multi worded and the name: field should not end with .vue. 
`sort-by="status" sortDesc`
You have a floating "sortDesc" thing here
You seemingly could benefit from using eslint.

**Comment by mlevet** [comment]
Thank you !
Now after updating I was able to use sort-by="status" (my column is sorted and I see the sorting Icon)
What if I want to be able to click any header to sort by Name or by Status, I thought sortable: true on my rows would do that

**Comment by VividLemon** [comment]
I'm sorry, I don't quite understand what you mean.

**Comment by mlevet** [comment]
Sorry, i have edited my question

**Comment by VividLemon** [comment]
You should be able to click either header and it should sort by that field, correct. the sortable property indicates that a field _can_ be sorted by. Whereas false means it cannot be. It may have been broken in the latest release. There has been many changes to that component. Try downgrading to [0.2.13](https://github.com/cdmoro/bootstrap-vue-3/releases/tag/v0.2.13)

**Comment by VividLemon** [comment]
@devhus can you look into this? It seems an addition you may have made has subsequently broken the sort feature

**Comment by devhus** [comment]
@mlevet Have you tried to add the `sortable` prop? i don't see it anywhere in your component.

**Comment by mlevet** [comment]
Thank you but still no success
I have both downgraded to 0.2.13
and added
props: ['sortable']

**Comment by devhus** [comment]
> Thank you but still no success I have both downgraded to 0.2.13 and added props: ['sortable']

Sorry, i have mixed it up with a recent added prop ``selectable`` .
Anyways, The table seems to be working fine with me.

You have to update your table props to support v-model updates
```vue
    <b-table
        sort-by="status" sortDesc
    >
```
to
```vue
    <b-table
        v-model:sort-by="status" 
        v-model:sortDesc
    >
```

In vue 3 ``v-model`` prop is the replacement for .sync attribute. so without it, the table does not update anything when clicking a header.

**Comment by VividLemon** [comment]
Clearly, I have little knowledge on how BTable is working.

**Comment by mlevet** [comment]
weirdly enough the v-model:sort-by="status" syntax doesn't work for me,
I still can't click on header but also it makes me loose the default sorting by status (which i have if i use sort-by="status")

**Comment by devhus** [comment]
> > with a bit of change to support vue3.
> 
> In that case, would you mind writing a note here about any changes that differ from BV, and it will be used when the docs for that component are expanded?

I think i do that in all of my PR

**Comment by devhus** [comment]
> weirdly enough the v-model:sort-by="status" syntax doesn't work for me, I still can't click on header but also it makes me loose the default sorting by status (which i have if i use sort-by="status")

Make sure to also pass the ``v-model:sort-desc`` prop

**Comment by mlevet** [comment]
Really banging my head to make it work
Would be so helpful to see a working example on jsfiddle if you could

**Comment by devhus** [comment]
@mlevet a fully working example, note that the 'sorted' event is bugged and will have a PR now to fix it.

```
<template>
  <b-container>
    <div>
      <b-table
        :items="items"
        :fields="fields"
        v-model:sort-by="sortBy"
        v-model:sort-desc="sortDesc"
        :sort-internal="true"
        @sorted="sortChanged"
      ></b-table>

      <div>
        Sorting By: <b>{{ sortBy }}</b>, Sort Direction:
        <b>{{ sortDesc ? 'Descending' : 'Ascending' }}</b>
      </div>
    </div>
  </b-container>
</template>

<script  lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  data() {
    return {
      sortBy: 'age',
      sortDesc: false,
      fields: [
        { key: 'last_name', label: 'last_name', sortable: true },
        { key: 'first_name', label: 'first_name', sortable: true },
        { key: 'age', label: 'age', sortable: true },
        { key: 'isActive', label: 'isActive', sortable: false }
      ],
      items: [
        { isActive: true, age: 40, first_name: 'Dickerson', last_name: 'Macdonald' },
        { isActive: false, age: 21, first_name: 'Larsen', last_name: 'Shaw' },
        { isActive: false, age: 89, first_name: 'Geneva', last_name: 'Wilson' },
        { isActive: true, age: 38, first_name: 'Jami', last_name: 'Carney' }
      ]
    }
  },
  methods: {
    sortChanged(sortBy: string, isDesc: boolean) {
      console.log(sortBy, isDesc);
    }
  }
});
</script>
```

![image](https://user-images.githubusercontent.com/58523735/187898328-60c3b32a-537c-450e-9b62-09854282a0d1.png)

**Comment by mlevet** [comment]
Thank you so much it worked !

**Comment by devhus** [comment]
> Thank you so much it worked !

What were missing ? Let me so i can fix it in case it was a bug.

**Comment by mlevet** [comment]
Seems v-model is needed
And also to pass the value as prop and not directly
```
        v-model:sort-by="sortBy"
        v-model:sort-desc="sortDesc"
```
