### ISSUE TITLE
data.index broken on b-table ?

### ISSUE THREAD

**Issue by mlevet** [cdmoro/bootstrap-vue-3#637]
My b-table is suddenly broken after update
the data.value is good but it seems the data.index is not incrementing (stucked to 0)
could it be a bug ?

```
<template>
    <b-table
        :items="items"
        :fields="formFields"
    >
      <template v-slot:cell(name)="data">
        <span :class="`name_${data.index}`">{{ data.value }}</span>
      </template>
    </b-table>
</template>

<script>

export default {
  data(){
    return {
      formFields: [
        {key: "name", label: "Name"},
        {key: "status", label: "Status"},
      ],
      items: [
        { name: "Jack", status: "Used" },
        {name: "Frank", status: "Unused"},
        {name: "Larry", status: "Used" },
      ],
    }
  },
}
</script>
```

**Comment by mlevet** [comment]
Fyi, i'm now using this instead of data.index
data.items.findIndex(p => p == data.item)

**Comment by VividLemon** [comment]
@devhus Do you mind figuring out a solution for why this broke? Eventually, when the issues and changes slow, I will start writing the tests for the component, so stuff like this wont occur.

**Comment by devhus** [comment]
Will give it a look in a bit
