### ISSUE TITLE
BCarousel doc is missing

### ISSUE THREAD

**Issue by dagnelies** [cdmoro/bootstrap-vue-3#645]
Hi,

I noticed the component exists: https://github.com/cdmoro/bootstrap-vue-3/blob/main/packages/bootstrap-vue-3/src/components/BCarousel/BCarousel.vue

However, the doc is missing: https://cdmoro.github.io/bootstrap-vue-3/components/

It would be great to be available! Thanks for this nice library, I also find it's source code more understandable than the original one ;)

**Comment by VividLemon** [comment]
Indeed, few components are missing from the docs. Today, I added in the missing ones. They only contain component references and some seem to be broken. It is a work in progress as the methods employed to get them to work are a bit hacky 😞 Or me just not knowing the docs well enough.

**Comment by VividLemon** [comment]
Somewhere along the lines, the example I had, broke. Clearly, it needs to be fixed.
