### ISSUE TITLE
Sorting broken on 0.3.2

### ISSUE THREAD

**Issue by mlevet** [cdmoro/bootstrap-vue-3#648]
Just upgraded from 0.2.13 to 0.3.2 to benefit from the latest data.index fix on b-table (which works) but the sorting seems now broken

```
<template>
    <b-table
        :items="items"
        :fields="formFields"
        v-model:sort-by="sortBy"
        v-model:sort-desc="sortDesc">
    >
      <template v-slot:cell(name)="data">
        <span :class="`name_${data.index}`">{{ data.value }}</span>
      </template>
    </b-table>
</template>

<script>

export default {
  data(){
    return {
      sortBy: 'name',
      sortDesc: false,
      formFields: [
        {key: "name", sortable: true, label: "Name"},
        {key: "status", sortable: true, label: "Status"},
      ],
      items: [
        { name: "Jack", status: "Used" },
        {name: "Frank", status: "Unused"},
        {name: "Larry", status: "Used" },
      ],
    }
  },
}
</script>


```

**Comment by VividLemon** [comment]
I suggest waiting for 0.3.3 as many BTable systems were overhauled.

**Comment by VividLemon** [comment]
> I don't think that sorting is broken, You are missing the `sort-internal(boolean)` prop which allows you to sort the displayed items internally instead of re-fetching your data using the `sorted` event

What exactly does the sort-internal prop do?

**Comment by devhus** [comment]
> > I don't think that sorting is broken, You are missing the `sort-internal(boolean)` prop which allows you to sort the displayed items internally instead of re-fetching your data using the `sorted` event
> 
> What exactly does the sort-internal prop do?

Determine if the table will sort its internal items or you will sort the given items prop yourself which is useful when you want to sort the table through API request within the ``sorted`` event
It was mentioned in this PR https://github.com/cdmoro/bootstrap-vue-3/pull/594

And its default value changed to ``false`` based on this comment
https://github.com/cdmoro/bootstrap-vue-3/pull/609#discussion_r959044777

**Comment by VividLemon** [comment]
> Determine if the table will sort its internal items or you will sort the given items prop yourself which is useful when you want to sort the table through API request within the `sorted` event It was mentioned in this PR #594
> 
> And its default value changed to `false` based on this comment [#609 (comment)](https://github.com/cdmoro/bootstrap-vue-3/pull/609#discussion_r959044777)

https://github.com/cdmoro/bootstrap-vue-3/commit/aac2b68f7bc8672246107c650e7c928dd336c201 Yeah, I turned it to true. I think my point was that it didn't have a default value... But did not fully understand how it worked, default true is better since most people don't need to sort by apis and stuff.

**Comment by VividLemon** [comment]
Update to 0.3.3 as sortInternal is default true, (fixes your issue). Or manually set prop sortInternal to true.
