### ISSUE TITLE
Global configuration and PaginationNav component

### ISSUE THREAD

**Issue by makroxyz** [cdmoro/bootstrap-vue-3#662]
Any plan for BPaginationNav and the possibility to global config components?

example:
```
app.use(BootstrapVue3, {
    BLink: {
        routerComponentName: 'inertia-router-link'
    },
    BModal: {
        cancelTitle: i18n.tc('app.cancel'),
    },
    /.......
}

**Comment by VividLemon** [comment]
None of the components have global config available. Perhaps sometime "soon", considering there isn't a whole lot left to complete. I just need to learn how to actually build this.
