### ISSUE TITLE
Pressing the escape key closing a <BModal> does not emit an update to v-model value.

### ISSUE THREAD

**Issue by Atokulus** [cdmoro/bootstrap-vue-3#674]
Hey community
I hope you are all well.

I just realized, that when showing a `<BModal>` and closing the modal with the escape key, the modal's v-model binding is not updated, leading to issues when wanting to reshow the modal.

See https://codesandbox.io/s/modal-close-bug-9sqsl6?file=/src/App.vue for a reproduction of this issue.

This issue has the same systemic root cause as #657, as `bootstrap-vue-3`'s events are quite detached from `bootstrap`'s events. This might or should raise concern, whether it is really manageable to predict and cover these often unapparent corner cases, or whether there should be another strategy, such as #658.

Best regards
Markus

**Comment by devhus** [comment]
I didn't even know that the Modal can be closed using the escape-key 🤣 
However, I still believe that the component should not depend on Bootstrap's events in such a matter.
IMO, A possible solution is to disable the feature from bootstrap's modal so it can no longer close the modal by pressing the escape key and implement that feature using vue's code to maintain stability for the component's props/refs.

The same solution was used to improve BModal to have multiple instances with correctly shown backdrops for each modal, Before that solution, the BModal component had no ability to have multiple instances shown nor have nested modals and, i believe that the same solution should be applied for this matter in BTable component.

**Comment by VividLemon** [comment]
I have been trying to write something that is impartial. But it's best to keep things internally handled by Vue. One of the biggest issues between incorporating a JS script into Vue is when they both attempt to modify the DOM at the same time. Though it's overhead for us, it's best to try to have things handled by Vue.

**Comment by Atokulus** [comment]
Dear @devhus and @VividLemon 
I can totally support this side as well, as it gets much more clear for the developer to read bootstrap-vue-3's code, so in the end it does not really matter to me.

Please just consider there are currently and in the future many more UX concepts e.g. for impaired people, and bootstrap seems to handle them quite well. It can get frustrating to keep up with this changes quite fast 😉

Best regards and many thanks for your insights 😀
Markus

**Comment by Atokulus** [comment]
Just another perspective: There might be a valid UX-Unit-Test in the future to just these corner-cases (Escape, Aria, Back key (?)).

**Comment by VividLemon** [comment]
> Just another perspective: There might be a valid UX-Unit-Test in the future to just these corner-cases (Escape, Aria, Back key (?)).

Due to the teleport in BModal, I was having issues when targeting the component when component testing. As such, BModal is not currently covered by tests. Eventually it will contain tests for all of those.
