### ISSUE TITLE
How to get hot-reloads working with pnpm dev?

### ISSUE THREAD

**Issue by dagnelies** [cdmoro/bootstrap-vue-3#682]
Hi,

I don't know if I missed something but `pnpm dev` at the project's root does not seem to pick up changes you make in the component files. ...and launching the `pnpm build` each time is kind of unproductive.

It's even described here: https://github.com/cdmoro/bootstrap-vue-3/blob/main/CONTRIBUTING.md#developing

Did I miss something or is this the normal workflow to build the whole thing each time before you visualize your change?

**Comment by VividLemon** [comment]
Open the one for bootstrap vue 3, and add modify the app. Vue for what you're trying to watch. 

The wording is poor there, I'll make it better later today

**Comment by dagnelies** [comment]
Ah, thanks for updating the message, the previous version was quite puzzling. 👍 😅 Since editing a message does not send a notification, writing a new message might help making the participants aware of the update

This helps, I'll follow that route, working with `./packages/bootstrap-vue-3/src/app.vue` is just fine too. ...now let's see if I can do something to fix this carousel, no guarantees.  😅
