### ISSUE TITLE
BTableSimple and internal BTableContainer similar

### ISSUE THREAD

**Issue by VividLemon** [cdmoro/bootstrap-vue-3#686]
@devhus 
The internal component BTableContainer that you have been using as a wrapper for BTable is awfully simple to that of BTableSimple. Could BTable use the BTableSimple wrapper instead, and remove the BTableContainer component?

**Comment by devhus** [comment]
I have no clue about BTableSimple tbh never used it before nor seen its code, i will take a look soon to understand your request

**Comment by devhus** [comment]
Yeah... after looking and the code, I know how it looks 😆 I haven't seen the BTableSimple code before but it looks like I've copy-paste its code to BTableContainer.
Shocked to see that i've wite a code that was already written.
Anyways, yes.. i will replace BTableContainer with BTableSimple

**Comment by VividLemon** [comment]
Some of the classes props and things could be moved over as well, and hand that functionality off to table simple

**Comment by devhus** [comment]
I will keep the updates simple at the moment so we don't have any more major updates to the table and you can finally push #666 release,
We can continue moving some logic to BTableSimple after but for now, I think we can just use BTableSimple as it is.

**Comment by VividLemon** [comment]
> I will keep the updates simple at the moment so we don't have any more major updates to the table and you can finally push #666 release, We can continue moving some logic to BTableSimple after but for now, I think we can just use BTableSimple as it is.

I'd prefer to have it finished before I publish that change.

**Comment by devhus** [comment]
> > I will keep the updates simple at the moment so we don't have any more major updates to the table and you can finally push #666 release, We can continue moving some logic to BTableSimple after but for now, I think we can just use BTableSimple as it is.
> 
> I'd prefer to have it finished before I publish that change.
> 
> If you're done with any changes, I will most likely build off of it a bit, and make some more tests tomorrow.

Unfortunately, I am busy for a couple of days and won't be able to work on major changes atm.
I believe that you can publish the release as it is for now if you'd like ofc.
