### ISSUE TITLE
Where can i find stepper?

### ISSUE THREAD

**Issue by syukriyansyah-ipb** [cdmoro/bootstrap-vue-3#710]
I want to create a process using stepper like as https://mdbootstrap.com/docs/b4/vue/components/stepper/.

**Comment by VividLemon** [comment]
It's unlikely this component would ever be made, especially prior to a v1.0. This is neither a Bootstrap or bootstrap-vue component. Maybe in the far future this library could be reviewed and some components could be ported over, but there's a lot to do before getting to that point.

**Comment by dagnelies** [comment]
@syukriyansyah-ipb Have you designed such a component in the meantime? I'm looking for that too.
