### ISSUE TITLE
Component b-nav-item multiple props combined issue

### ISSUE THREAD

**Issue by vkovalev-mjhs** [cdmoro/bootstrap-vue-3#713]
Component **b-nav-item** rendered doesn't have "active" class when combined with prop **to**

    <b-nav tabs>
       <b-nav-item active>Home</b-nav-item>
    </b-nav>

is good.

    <b-nav tabs>
       <b-nav-item active to="/Home">Home</b-nav-item>
    </b-nav>

doesn't have "active" class.

**Comment by VividLemon** [comment]
There's a bug on the <a> element... `<a text="foo">bar</a>` in vue, it renders "foo" instead of "bar". This should not be happening. Regardless, it is fixed https://github.com/cdmoro/bootstrap-vue-3/pull/715

**Comment by VividLemon** [comment]
Not sure if this is the best solution, but https://github.com/cdmoro/bootstrap-vue-3/pull/719
