### ISSUE TITLE
Implementation of BFormRadio bound to an array not compatible with bootstrap-vue

### ISSUE THREAD

**Issue by jclijmans** [cdmoro/bootstrap-vue-3#72]
When you bind some BFormRadio components to the same array, the behavior of the radio's is not compatible with bootstrap-vue

In bootstrap-vue, only 1 radio can be selected at any time.
In bootstrap-vue-3 implementation, multiple radio's can be selected.

I created this issue to discuss the implementation.

In my opinion, we should be compatible with bootstrap-vue

**Comment by cdmoro** [comment]
I think the same, we should keep stick to BootstrapVue components behavior.

**Comment by Geoffrey-D** [comment]
implemented in https://github.com/cdmoro/bootstrap-vue-3/pulls
