### ISSUE TITLE
Events propagate through BButton Click

### ISSUE THREAD

**Issue by alexdohm** [cdmoro/bootstrap-vue-3#723]
If a button is clicked, the event propagates which can cause unwanted behavior. This can be mitigated with a workaround like @click.stop. I'm not sure if this was intentional by you but wanted to bring it up.

The use case I had was a table has clickable rows. Each row also has a button. If I clicked on a button, I would also activate the click on the row, which I did not want to do.

    "bootstrap": "^5.2.0",
    "bootstrap-vue-3": "^0.3.7",

**Comment by VividLemon** [comment]
Are you saying that this is solely an issue in the table component? Or that there's multiple issues here. Realistically, why could you not use .stop? And not prevent others that would prefer it (nobody would probably prefer it though lmao, or really care). I'll also review bootstrap vue behavior as well. Just trying to see how large of an issue this may be, and if it's something that _should_ be changed

**Comment by VividLemon** [comment]
@devhus assuming I can understand how this works, https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/table/helpers/filter-event.js would you consider assisting with the implementation of this event filtering

**Comment by devhus** [comment]
Sure, i am aware of the issue long time ago but i forgot to fix it completely.
I will do it once i get some free time

**Comment by VividLemon** [comment]
> Sure, i am aware of the issue long time ago but i forgot to fix it completely. I will do it once i get some free time

K

**Comment by devhus** [comment]
This issue will be resolved in my next PR, Sorry for the delay.
