### ISSUE TITLE
BFormRadio warning when bound to an object

### ISSUE THREAD

**Issue by jclijmans** [cdmoro/bootstrap-vue-3#73]
When a BFormRadio is bound to an object, in development mode following warning is displayed
[Vue warn]: Invalid prop: type check failed for prop "modelValue". Expected Boolean | String | Array, got Object

The prop modelValue definition does not specify the Object option.

This is a warning in development, but I'm not sure if it doesn't create an error in production mode.

**Comment by cdmoro** [comment]
Let me ask you a question, despite that warning, the behavior it's correct when you bound it to an Object? If the answer is yes, I believe it's as simple as changing the prop type inside the component.

**Comment by jclijmans** [comment]
Yes, the behavior is correct. It is indeed a matter of changing the property type definition.
I've tried that, but then other typescript errors appear.
So it needs a bit more TLC

**Comment by Geoffrey-D** [comment]
I agree that the former implementation that has been kept (behaving like checkboxes) was not correct.

This should be solved in https://github.com/cdmoro/bootstrap-vue-3/pulls
