### ISSUE TITLE
Modal dialog style doesn't work

### ISSUE THREAD

**Issue by Zoey1988** [cdmoro/bootstrap-vue-3#733]
### Describe the bug

It seems that scoped styles are not included in the `bootstrap-vue-3/dist/bootstrap-vue-3.css`.

Example:

`.modal-dialog {
  z-index: 1051;
}`

This style does not get applied when using a modal.

**Comment by Zoey1988** [comment]
It was ok on version 0.3.7, but when we upgraded to 0.3.11, this issue happend.
As you can see in first screenshot, dialog doesn't have the proper z-index.
I deleted node-modules and installed everything again, now the problem is that data attributes are not the same on the element and in the css.

![first screenshot](https://user-images.githubusercontent.com/35141243/194036934-1e4d600c-3853-42b5-a1fb-356358f3b099.png)

![image](https://user-images.githubusercontent.com/35141243/194037737-446e10c4-7b37-4a2c-9d60-3c3375fdbbe5.png)
![image](https://user-images.githubusercontent.com/35141243/194037852-8b3e6d02-4378-49db-9317-98d63744596b.png)

**Comment by VividLemon** [comment]
There's simply nothing that I can do with this information without a replication. From a fresh install on my end, everything is correct. Though unlikely, I would assume something was done on your end that prevents the modal from getting the correct data-v-attr. Hypothetically could could attach the correct data attribute, don't think it would cause problems.

**Comment by Zoey1988** [comment]
As you guessed it was an issue in our project, after deleting node-modules and installing again, it's working now.
