### ISSUE TITLE
Participate in hacktoberfest ;) 

### ISSUE THREAD

**Issue by dagnelies** [cdmoro/bootstrap-vue-3#739]
https://hacktoberfest.com/

Just a suggestion ;)

**Comment by VividLemon** [comment]
Im interested, but a bit confused on what exactly it is

**Comment by VividLemon** [comment]
Disappointingly, even with collaborator privileges, I am unable to modify the "Topics" section for the project. As such, I am not able to add the required topic to be eligible. 

Regardless, I find that most of the issues in the library have become more difficult issues, that one would need to spend a bit longer amount of time to diagnose and fix. Not sure how many people would be willing to learning the library and helping.

**Comment by dagnelies** [comment]
Well, that's a pity. Let's simply close it then.
