### ISSUE TITLE
ModelValue not updating to false on closing the Modal using the cross(X) button on header

### ISSUE THREAD

**Issue by neo7337** [cdmoro/bootstrap-vue-3#743]
**Describe the bug**
The modal has a header where the (X) button is present which is meant to close the button. But I noticed that it closes the modal but on clicking the button again to open the modal the modal does not open. So I further investigated the props value using the Vue extension and noticed that the modelValue is not getting updated on hide.

**Expected behavior**
Expected behaviour should be the modal should toggle on on button click from which the action is taking place. If I click outside the modal it works correctly.

**Additional context**
Please refer to the hide() code which seems to working in flaw.
https://github.com/cdmoro/bootstrap-vue-3/blob/main/packages/bootstrap-vue-3/src/components/BModal.vue#L306

```
const hide = () => {
  if (modelValueBoolean.value) emit('update:modelValue', false)
  getInstance().hide()
}
```
this `modelValue` is not toggling.

**Comment by VividLemon** [comment]
I have a rough draft in the works that eliminates Bootstrapjs on Modal and will fix the complexity of dealing with both Vue and Bootstrapjs. Just dealing with it _always_ being lazy rendered...

**Comment by devhus** [comment]
This issue has been fixed before, what is the library version you are using ?

**Comment by neo7337** [comment]
I tried upgrading but library is breaking the existing functionality, not sure if anyone else facing issue after upgrade

**Comment by devhus** [comment]
> I tried upgrading but library is breaking the existing functionality, not sure if anyone else facing issue after upgrade

Well, that means you have another issue, since the X button issue was fixed the only solution for you is to upgrade the library
If it breaks after upgrading you should create an Issue for the break, not for an old issue that is fixed 
I advice you to do that and mention more details about what breaks with you.

**Comment by neo7337** [comment]
sure @devhus ! I will gather some more info and raise another issue.
We can close this issue as the issue I raised has already been addressed!

**Comment by VividLemon** [comment]
https://github.com/cdmoro/bootstrap-vue-3/pull/751/files#diff-9053fefc170f47ebfdc5d697fb953cb52923055e78a52e94e3f526e14315f09f
