### ISSUE TITLE
Modal: Migrate from BoostrapVue + vue2 to boostrap-vue-3 + vue3

### ISSUE THREAD

**Issue by stritti** [cdmoro/bootstrap-vue-3#766]
**What you are trying to do**
Currently I try to migrate from vue2 to vue3. We use in methods to show/hide modals like 
```
methods: {
  showModal() {
    this.$bvModal.hide("modal-x");
  }
}
```

How could this be done using boostrap-vue-3?

**What you have already tried**
Investigated in docs.

**Comment by VividLemon** [comment]
No, it's vmodels only. Not sure if it will be supported, mostly because im not sure how it's done, or if you can actually use those global method injections like shown in vue 3. 

Hypothetically you could achieve the same result with global state management like pinia. But with more boilerplate

**Comment by stritti** [comment]
Hm, okay. Thanks for reply. Global state sounds not like a perfect solution to show/hide modals.
