### ISSUE TITLE
v-b-toggle not working properly

### ISSUE THREAD

**Issue by lokoamigo** [cdmoro/bootstrap-vue-3#767]
**Describe the bug**
First of all, im new to nuxt and nuxt 3 especially so dont blame me if the error is on nuxts side.
To the Problem:
Whenever i try to use the v-b-toggle directive, the side wont render properly.

**To Reproduce**
I wanted to make an accordion as documented [here](https://cdmoro.github.io/bootstrap-vue-3/components/Collapse.html#trigger-multiple-collapse-elements). As soon as i use the v-b-toggle directive, the page wont render. I get a white screen. 

So far ive just pasted everything from the docs in app.vue and sorrounded it with <ClientOnly>-Tag. I removed their text string from script part and entered only some blank text in the <b-card-text>-Tag.

My app.vue looks as follows (sry for the png but markdown does not support such long code snippets i guess):

![output-seotoolscentre](https://user-images.githubusercontent.com/57625769/197603975-34d8f411-1f8c-454c-aa49-ea2b2e43525c.png)

**Expected behavior**
The Accordion gets rendered properly and is collapsable.

**Screenshots**
The page with v-b-toggle:
![image](https://user-images.githubusercontent.com/57625769/197601172-5a72e6ca-5ddf-4987-b598-f47e7c2e36dc.png)

The page with :v-b-toggle:
![image](https://user-images.githubusercontent.com/57625769/197602715-fb6f4be7-b797-4f5e-9813-f514b8f2358e.png)

**Environment (please complete the following information):**
im using the following frameworks:
nuxt 3 
nuxt content
bootstrap vue 3

**Comment by VividLemon** [comment]
Bootstrap-vue-3 is not SSR ready, and will have those issues. Nothing you have done is wrong, but I believe the issue comes from the fact that the directive is never loaded in and is pretty much inaccessible to Nuxt. The `this.$root` syntax will not work at all, or ever, in Vue3 script setup syntax.

**Comment by lokoamigo** [comment]
Thanks for your prompt answer. I know that my whole project architecture is very experimental, but i didn't imagine that my use case here is so hard to implement. 
Can you think of any workaround for this?
