### ISSUE TITLE
b-table filtering fails if items have null values

### ISSUE THREAD

**Issue by NNeto** [cdmoro/bootstrap-vue-3#770]
**Describe the bug**
Trying the working example on #643 but when an item have at least one null root property and I type something in the filter input, the filter doesn't work and the browser console shows `Uncaught (in promise) TypeError: can't convert null to object` on each keystroke.

**To Reproduce**
Steps to reproduce the behaviour:
1. Copy and paste the code of the working example on #643 
2. Edit one of the items in the `items` array, either changing one of the root properties to a null value or adding one new arbitrary property on the root of the object with null value (it doesn't need to be shown in the table in any column).
3. Type something into the filter input
4. Check the error on the dev tools console

**Expected behaviour**
Filtering should still work, treating the null values as empty strings.

**Screenshots**
![image](https://user-images.githubusercontent.com/7104467/197860058-0cb95471-c75f-4507-95d1-74d7ba1c6cbc.png)
Dickerson Macdonald with `age: null`

**Environment (please complete the following information):**
<details>
<summary>Click to expand</summary>

```shell
  System:
    OS: Linux 5.19 Fedora Linux 35 (Workstation Edition)
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz
    Memory: 1.13 GB / 15.45 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 8.19.0 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Firefox: 105.0.1
```
</details>

**Comment by VividLemon** [comment]
Stop finding broken stuff lmao

**Comment by devhus** [comment]
Who are you and how much did they pay you? 😆
