### ISSUE TITLE
Error  in ./node_modules/bootstrap-vue-3/dist/bootstrap-vue-3.es.js

### ISSUE THREAD

**Issue by yashwanth2714** [cdmoro/bootstrap-vue-3#772]
**Describe the bug**
We are getting the follow bootstrap-vue-3 error in node modules.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/36370530/198593614-3e8afe5c-07bf-44bf-8309-4119348200a4.png">

Please let us know what might be causing the issue.

Node Version: 14.17.3
NPM Version: 6.14.13

**Comment by VividLemon** [comment]
You probably didn't install the necessary peer dependencies

**Comment by yashwanth2714** [comment]
Yeah. I am installing "bootstrap" now. This may resolve the issue. I will update here.

**Comment by VividLemon** [comment]
Vue, bootstrap and @popperjs/core are all required peer dependencies.

**Comment by yashwanth2714** [comment]
Thanks! I don't see that error now.
