### ISSUE TITLE
Errors in documentation pages

### ISSUE THREAD

**Issue by papppeter** [cdmoro/bootstrap-vue-3#779]
**Describe the bug**
Maybe it is only for me but is see many errors in documentation pages. Which makes me hasitating to use this component.

**To Reproduce**
1. Go to https://cdmoro.github.io/bootstrap-vue-3/components/Overlay.html#form-confirmation-prompt-and-upload-status
2. Click on submit
3. there is no overlay
4. code lines are not all with black background

**Screenshots**
![image](https://user-images.githubusercontent.com/3380880/198823542-9d488939-6227-4f3d-bc27-71777eb89bea.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - lastest chrome

**Comment by VividLemon** [comment]
There isn't a "typical" overlay, because in the code below it, it's overwriting the overlay slot. The _Are you sure?_ blob **is** the overlay. Albeit, hideously overlapping the button.
