### ISSUE TITLE
BFormChexboxGroup ignores the required property

### ISSUE THREAD

**Issue by jclijmans** [cdmoro/bootstrap-vue-3#79]
BFormCheckboxGroup doesn't handle the required property.

According to the documentation :

>The name is required in order for Assistive Technologies (such as screen readers, and keyboard only users) to know which checkboxes belong to the same form variable (the name also automatically enables native browser keyboard navigation), hence required will only work if name is set. <b-form-checkbox-group> will automatically generate a unique input name if one is not provided on the group.

BFormCheckboxGroup does not set the required attribute even when name is also set

**Comment by Geoffrey-D** [comment]
implemented in https://github.com/cdmoro/bootstrap-vue-3/pull/84 :)
