### ISSUE TITLE
How to extend ColorVariant, ButtonVariant, etc.?

### ISSUE THREAD

**Issue by esl51** [cdmoro/bootstrap-vue-3#790]
**What you are trying to do**
I can extend bootstrap using scss. For example, add my own colors, sizes, etc.
But I can't use them.

**What you have already tried**
```vue
<b-button variant="purple">Purple button</b-button>
```

**Any error messages you are getting**
TS2322: Type '"purple"' is not assignable to type 'ButtonVariant | undefined'.

**Environment:**
 - OS: MacOS Monterey 12.6
 - Version: 0.3.12

**Comment by VividLemon** [comment]
Fundamentally the code would need to be rewritten on our end to support that. One would need to somehow override the ColorVariant interface. If it was directly modified in the dist, then it would be written over on subsequent installs. Not very intuitive. 

You could attempt to typecast - `'purple' as unknown as ColorVariant`

Doing as you reference would be a nice thing to support, but would require hefty discussions on how to best achieve it.

**Comment by aceofwings** [comment]
Please note that the prop type only applies the variant class to the given component . Make sure to follow color guide [here](https://getbootstrap.com/docs/5.0/customize/color/). You can also look at bootswatch for theming. This issue is beyond the scope of bootstrapvue.

**Comment by esl51** [comment]
> This issue is beyond the scope of bootstrapvue.

I can create [my own color maps](https://getbootstrap.com/docs/5.0/customize/sass/#add-to-map) with bootstrap

```scss
// Create your own map
$custom-colors: (
  "purple": $purple-500;
);

// Merge the maps
$theme-colors: map-merge($theme-colors, $custom-colors);
```

and then use them:

```html
<button class="btn btn-purple">Purple button</button>
```

but can't use them with bootstrap-vue.

I also can't solve it with class because BButton has default 'secondary' variant.

```vue
<b-button class="btn-purple">Purple button</b-button>
```
turns into this:
```html
<button class="btn btn-secondary btn-purple">Purple button</b-button>
```

Thereby, I think this issue is in the scope of bootstrap-vue.

**Comment by aceofwings** [comment]
As @VividLemon lemon mentioned this will be considered an enhancement.. However I think its better to address this in the docs on how to extend our library typing namespace then to write generic code to address this issue and thus use your types as needed.

**Comment by VividLemon** [comment]
> As @VividLemon lemon mentioned this will be considered an enhancement.. However I think its better to address this in the docs on how to extend our library typing namespace then to write generic code to address this issue and thus use your types as needed.

How would you like to move forward with https://github.com/cdmoro/bootstrap-vue-3/pull/791 ? Should it be closed? What would you like done with this issue? How do should we plan on solving it?

**Comment by aceofwings** [comment]
Looks good , I guess the only way to extend types right now are through interfaces and enum declarations. That was pretty quick

**Comment by VividLemon** [comment]
> Looks good , I guess the only way to extend types right now are through interfaces and enum declarations. That was pretty quick

Would you like to review and approve/disapprove the pr? Do you think it's an accessible way to accomplish the fix? 

I may go and look around in ts, I'm pretty sure there's ways to extend types without the hacky interface extend hack. Or maybe not and that's the only way, I'd be surprised if it was though, quite creative if it is.

**Comment by aceofwings** [comment]
I was exploring and couldn’t find much on using unions to extend the ButtonVariant type. I think it is the only solution right now but there is a typescript doc for extending namespaces. It is a very transparent change so I don’t mind merging it until something better comes along .

**Comment by VividLemon** [comment]
I'll review it again in the morning and go from there
