### ISSUE TITLE
Module does not provide an export named 'BIcon'

### ISSUE THREAD

**Issue by anitan027** [cdmoro/bootstrap-vue-3#797]
Does anyone encounter this error in b-icon?

Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/bootstrap-vue-3.js?v=55a0019c' does not provide an export named 'BIcon'

here's my dependencies

"devDependencies": {
    "@types/node": "^16.11.68",
    "@vitejs/plugin-vue": "^3.1.2",
    "@vue/tsconfig": "^0.1.3",
    "npm-run-all": "^4.1.5",
    "typescript": "~4.7.4",
    "unplugin-vue-components": "^0.22.9",
    "vite": "^3.1.8",
    "vue-tsc": "^1.0.8"
  }

**Comment by VividLemon** [comment]
Never seen it, no.

**Comment by anitan027** [comment]
So <b-icon> is not yet working?

**Comment by VividLemon** [comment]
It's a separate package and hasn't been published. So no. But im happy to see someone wants to try it

**Comment by anitan027** [comment]
@VividLemon Thank you

**Comment by MCatherine1994** [comment]
Hello everyone, I'm getting this similar error as well, "Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/bootstrap-vue-3.js?v=a06b4cab' does not provide an export named 'BIcon'". Wondering if the current boorstrap-vue-3 supports icon or not?

I'm using the icon as:
<b-icon icon="asterisk"></b-icon>

Followed preferred installation method: https://cdmoro.github.io/bootstrap-vue-3/getting-started/#preferred-installation

Thanks!!

**Comment by VividLemon** [comment]
> Hello everyone, I'm getting this similar error as well, "Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/bootstrap-vue-3.js?v=a06b4cab' does not provide an export named 'BIcon'". Wondering if the current boorstrap-vue-3 supports icon or not?
> 
> I'm using the icon as:
> 
> Followed preferred installation method: https://cdmoro.github.io/bootstrap-vue-3/getting-started/#preferred-installation
> 
> Thanks!!

https://github.com/cdmoro/bootstrap-vue-3/issues/797#issuecomment-1306531518

**Comment by aceofwings** [comment]
Well it might be time to start the organization at move to BV3 or something like that

**Comment by VividLemon** [comment]
> Well it might be time to start the organization at move to BV3 or something like that

What?

**Comment by aceofwings** [comment]
> 
> What?

Good Question, so who owns the secrets and how are they integrated into the build process? We cannot make a package underneath an organizational account similar to the original bootstrap vue?  Obviously I am keeping it simple but I am sure their is a lot more to consider.

**Comment by VividLemon** [comment]
> > What?
> 
> Good Question, so who owns the secrets and how are they integrated into the build process? We cannot make a package underneath an organizational account similar to the original bootstrap vue? Obviously I am keeping it simple but I am sure their is a lot more to consider.

Keeping it simple, Carlos is the only one that can modify that stuff. Yesterday, I sent him an email about converting to an organization. However, it can be difficult to get his attention, especially considering there is a decent time difference. 

Organizations are accounts themselves, but can organize a team. Members have permissions that are seemingly more granular than what we have currently. 

The goal for a merger has been to achieve the same result. As both ownership of bootstrap vue and this are difficult to get ahold of and both require an active owner. Github heavily suggests that organizations have more than one active owner.

**Comment by VividLemon** [comment]
Review the new documentation for https://cdmoro.github.io/bootstrap-vue-3/icons/ on how to incorporate icons into your package.
