### ISSUE TITLE
What is the reason for not adding the autofocus attribute to b-form-input?

### ISSUE THREAD

**Issue by esl51** [cdmoro/bootstrap-vue-3#799]
https://cdmoro.github.io/bootstrap-vue-3/components/FormInput.html#autofocus

> Note that this prop does not set the autofocus attribute on the input

What is the reason for this behavior? The point is that I want to make my own wrapper of `BModal` and automatically set the focus to a specific input when opening a modal window with a form. And in order to make this functionality as transparent as possible and not to add extra classes, I wanted to use `querySelector('[autofocus]')`. That way when a modal window is opened, the focus would be set to the element with the autofocus attribute, which would be logical.

```ts
// modal
const dialog = ref<HTMLElement | null>(null)

// autofocus input
const autofocusInput = computed(
  () => dialog.value?.querySelector('[autofocus]') as HTMLElement
)

// show method of my dialog component
const show = () => {
  // ...
  autofocusInput.value?.focus()
}

// exposing method
defineExpose({ show })
```

**Comment by VividLemon** [comment]
The autofocus attribute spec only focuses when the *page* is loaded. So it doesn't really work well with the nature of an SPA.

**Comment by esl51** [comment]
> The autofocus attribute spec only focuses when the page is loaded. So it doesn't really work well with the nature of an SPA.

I know, but we could just add it in there. For backward compatibility or something. That wouldn't break anything, would it? In general, okay, I get the reason. Thank you.
