### ISSUE TITLE
Dependency bootstrap-vue-3-icons not on npmjs.com

### ISSUE THREAD

**Issue by jonkad** [cdmoro/bootstrap-vue-3#815]
Installation of bootstrap-vue-3@0.4.9 requieres bootstrap-vue-3-icons , but that package is not available on npmjs.com

**Comment by VividLemon** [comment]
@aceofwings

**Comment by aceofwings** [comment]
I see it. I am going to  just use text string instead of icons until we put an icons into the main package.
