### ISSUE TITLE
Null State property is not working for some HTML elements

### ISSUE THREAD

**Issue by mamartinezmejia** [cdmoro/bootstrap-vue-3#819]
The **null** state property for the following elements doesn't work:
_b-form-checkbox
b-form-radio
b-form-select_

It works only for the _b-form-input_ element

**Comment by VividLemon** [comment]
Duplicate of #807 . Though your issue has slightly more useful information

**Comment by mamartinezmejia** [comment]
Thanks, @VividLemon. Do you have a deadline to revise this issue?

**Comment by VividLemon** [comment]
There has been no changes on this issue. Sorry
