### ISSUE TITLE
BFormCheckbox with v-model not working 

### ISSUE THREAD

**Issue by TusharJoy** [cdmoro/bootstrap-vue-3#831]
**Description**
straight example from documentation also does not work. I am using options API.

**Parent Component**
```
      <b-form-checkbox v-model="switchChecked" switch>
        Switch Checkbox <strong>(Checked: {{ switchChecked }})</strong>
      </b-form-checkbox>
```

**Screenshots**

![Screenshot from 2022-12-09 12-06-34](https://user-images.githubusercontent.com/13586994/206636118-a6c73b31-1976-43fe-ba62-64c304dd35d5.png)

Way around is i had to use explicit binding using 

```
        <b-form-checkbox @update:modelValue="switchChecked = !switchChecked" :checked="switchChecked"  switch>
          Switch Checkbox <strong>(Checked: {{ switchChecked }})</strong>
        </b-form-checkbox>
```
I also had similar experience using other components v-model does not work in my use case.

**Comment by VividLemon** [comment]
I tried with 
```html
<template>
  <b-form-checkbox v-model="switchChecked" switch>
    Switch Checkbox <strong>(Checked: {{ switchChecked }})</strong>
  </b-form-checkbox>
  <b-button @click="switchChecked = !switchChecked">Click me</b-button>
</template>

<script lang="ts">
import {defineComponent} from 'vue'

export default defineComponent({
  data() {
    return {
      switchChecked: false,
    }
  },
})
</script>
```

```html
<template>
  <b-container>
    <b-row>
      <v-col>
        <b-form-checkbox v-model="switchChecked" switch>
          Switch Checkbox <strong>(Checked: {{ switchChecked }})</strong>
        </b-form-checkbox>
      </v-col>
    </b-row>
  </b-container>
</template>

<script setup lang="ts">
import {ref} from 'vue'

const switchChecked = ref(false)

</script>
```
And was unable to replicate the checkbox not working. Soon I will be updating the checkbox and other similar components to match more closely with Bootstrap-vue with this issue https://github.com/cdmoro/bootstrap-vue-3/issues/813 . But your issue seems unrelated.

**Comment by TusharJoy** [comment]
@VividLemon Thanks for the feedback i got the issue in my case as i was using  [Vue migration](https://www.npmjs.com/package/@vue/compat) tools to migrate my Vue 2 project to Vue 3 that was the culprit as iwaas running it in Vue2 mode after running it independently on Vue 3 everything works fine, So i am closing the issue.
