### ISSUE TITLE
can't find the nuxt.ts module from 0.4.14

### ISSUE THREAD

**Issue by tomomo** [cdmoro/bootstrap-vue-3#835]
**Describe the bug**
I tried to install it on Nuxt3 according to the manual, but I get an error.
```
ERROR Cannot find module ... /node_modules/bootstrap-vue-3/nuxt.ts
```

**To Reproduce**
I set it up according to this manual.
https://cdmoro.github.io/bootstrap-vue-3/getting-started/#installation-nuxt-js-3
```
export default defineNuxtConfig({
  modules: ['bootstrap-vue-3/nuxt'],
  css: ['bootstrap/dist/css/bootstrap.css'],
})
```
It seems that `/node_modules/bootstrap-vue-3/nuxt.js`, which existed until 0.4.13, does not exist in 0.4.14.

**Environment (please complete the following information):**
 - OS: Mac 11.7
 - Version 0.4.14.

**Comment by oleynikyurij** [comment]
@tomomo Faced a similar problem. I tried to add a file "nuxt.ts" from the previous version and it started.

**Comment by VividLemon** [comment]
https://github.com/cdmoro/bootstrap-vue-3/releases/tag/v0.4.15
