### ISSUE TITLE
"b-alert" may not work during nuxt3 SSR.

### ISSUE THREAD

**Issue by tomomo** [cdmoro/bootstrap-vue-3#839]
**Describe the bug**
In case of nuxt3, `b-alert` may not work.

```
[Vue Router warn]: uncaught error during route navigation:
ReferenceError: document is not defined
    at enableDismissTrigger (/Users/xxx/Workspace/nuxt3-bootstrap-study/node_modules/bootstrap/dist/js/bootstrap.js:888:21)
```

**To Reproduce**
It can be reproduced with nuxt3 environment construction.
```
<b-alert show>Default Alert</b-alert>
```

However, if you set `ssr: false`, it seems to work.
- nuxt.config.ts
```
export default defineNuxtConfig({
  ssr: false,
```

**Environment**
 - OS: MacOS
 - Version 0.4.15
 - Nuxt 3.0.0

**Comment by VividLemon** [comment]
https://github.com/cdmoro/bootstrap-vue-3/projects/5

**Comment by tomomo** [comment]
Understood.
Thanks for the reference link.
