### ISSUE TITLE
Unable to show modal dialog

### ISSUE THREAD

**Issue by timvol** [cdmoro/bootstrap-vue-3#863]
**What you are trying to do**
I'm trying to show a very simple modal.

**What you have already tried**
I've the following source of my vue component:

```
<template lang="pug">
b-button(@click="modalShow = true") open
b-modal(v-model="modalShow") Hello World
</template>

<script>
export default {
  data() {
    return {
      modalShow: false
    }
  }
}
</script>
```

I can see a button "open" appears, but when I click on the button, nothing happens... no error message nor warning in the console. I also integrated the lines above into my vue component where I need it and there I'm getting the following warnings when I press "open":

![image](https://user-images.githubusercontent.com/59340447/211099209-f8ed6e89-2ebd-4c3c-bffa-6fad1d459833.png)

I also checked out the documentation on https://cdmoro.github.io/bootstrap-vue-3/components/Modal.html but unfortunately it didn't helped me a lot on this problem. Any ideas what might cause the error?

**Environment (please complete the following information):**
 - OS: Windows 11
 - Version 0.4.14
- Node.js: 18.12.1

**Comment by VividLemon** [comment]
First try deleting your node_modules folder, and reinstalling. If that doesn't work, please create a sandbox, I don't have much experience with pug and would like to play around with it

**Comment by timvol** [comment]
I was finally able to solve the issue by myself. I was missing the following line in my vue application (using the legacy installation method atm):

```
import 'bootstrap-vue-3/dist/bootstrap-vue-3.css'
```

After adding this line, the modal appears. Thank you @VividLemon for your support!

**Comment by makroxyz** [comment]
importing 'bootstrap-vue-next/src/styles/styles.scss' BModal doesn't work

**Comment by phlegx** [comment]
@makroxyz I have imported `bootstrap-vue-next/src/styles/styles.scss` but the modal is not shown. The `body` get class `modal-open` and the modal itself has class `modal show`. But the `.modal` CSS class has `display: none` and there is no CSS that sets the modal to `display: block` if class `show` is present on the modal node.
