### ISSUE TITLE
Cannot find module 'bootstrap-icons/bootstrap-icons.svg' or its corresponding type declarations

### ISSUE THREAD

**Issue by Geoffrey-D** [cdmoro/bootstrap-vue-3#89]
Being able to import "bootstrap-icons.svg" in BIcon.vue in a Typescript project require the following config in the project file `src/custom.d.ts`:

```
declare module "bootstrap-icons/*.svg" {
  const path: string;
  export default path;
}
```

Without this file, the following error is generated:
`TS2307: Cannot find module 'bootstrap-icons/bootstrap-icons.svg' or its corresponding type declarations.
`

I think that we need to specify this somewhere in the documentation!

**Comment by cdmoro** [comment]
Or we could declare this module inside [BootstrapVue.d.ts](https://github.com/cdmoro/bootstrap-vue-3/blob/f872a310a5da4b85d14c1f1c4c4978f6953c823c/src/BootstrapVue.d.ts), what do you think?

**Comment by Geoffrey-D** [comment]
Declaring it directly on the lib would be indeed better.

However, adding the code in BootstrapVue.d.ts (or shims-vue.d.ts) is not working.

Do you have any idea?

Alternatively we could allow the `//ts-ignore`

**Comment by Geoffrey-D** [comment]
solved by https://github.com/cdmoro/bootstrap-vue-3/pull/98 (TS compilation is done only when the `/dist` folder is not present)
