### ISSUE TITLE
BDropdown does not expose the hide method on the default slot

### ISSUE THREAD

**Issue by jclijmans** [cdmoro/bootstrap-vue-3#95]
In Bootstrap-vue, the BDropdown has the `hide` method in the scope of the default slot. This method can be used to manually close the dropdown.

Usage of this feature can be a b-dropdown-form where you want to submit a form and close the dropdown after successful completion.

Are we going to export this method on the scope?
I'm currently making the docs for BDropdown and have for now not documented the scope nor the b-dropdown-form because I could not create a working sample.

**Comment by Geoffrey-D** [comment]
implemented in PR https://github.com/cdmoro/bootstrap-vue-3/pull/117

To test it: 
```
<b-dropdown ref="dropdown" text="Drowdown" auto-close="outside">
    <b-button>Basic button</b-button>
    <b-button variant="primary" @click="this.$refs.dropdown.hide()">Close dropdown</b-button>
</b-dropdown>
```

NB: the focus param is not implemented yet

**Comment by cdmoro** [comment]
I've just merged @Geoffrey-D PR, so I'm gonna close this issue
